import { randomUUID } from "node:crypto";
import { and, eq, inArray, isNull } from "drizzle-orm";
import { db } from "@/lib/db";
import { businessFields, businessObjects, businessRelationships, dashboardAiRecommendations, dashboardBlocks, dashboardVersions, kpiDefinitions } from "@/lib/db/schema";
import type { AuthenticatedUser } from "@/lib/auth/session";
import { hasPermission } from "@/lib/auth/permissions";
import { HttpError } from "@/lib/http";
import { requireDashboardAccess } from "./permissions";
import { validateVisualization } from "./rules";
import { dashboardRecommendationSchema, type DashboardRecommendation } from "./ai-schema";

function aiConfig() { const apiKey = process.env.AI_API_KEY; const baseUrl = process.env.AI_BASE_URL?.replace(/\/$/, ""); const model = process.env.AI_MODEL; if (!apiKey || !baseUrl || !model) throw new HttpError(503, "AI assistance is not configured", "AI_NOT_CONFIGURED"); return { apiKey, baseUrl, model, provider: process.env.AI_PROVIDER || "openai-compatible" }; }
function safeJson(value: string) { const cleaned = value.replace(/^```json\s*/i, "").replace(/```$/i, "").trim(); return JSON.parse(cleaned) as unknown; }

export async function requestDashboardRecommendation(dashboardId: string, request: { dashboardBlockId?: string; requestType: DashboardRecommendation["recommendationType"]; instruction?: string }, user: AuthenticatedUser) {
  if (!hasPermission(user.role, "USE_COPILOT")) throw new HttpError(403, "AI assistance is not permitted", "FORBIDDEN"); const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.aiCopilotAllowed) throw new HttpError(403, "AI assistance is disabled for this dashboard", "AI_DISABLED"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "AI recommendations can be requested only for a draft", "IMMUTABLE_VERSION"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentDraftVersionId)).limit(1))[0];
  const [objects, fields, relationships, kpis, blocks] = await Promise.all([db.select({ id: businessObjects.id, businessName: businessObjects.businessName, description: businessObjects.description, objectType: businessObjects.objectType, recordGrain: businessObjects.recordGrain }).from(businessObjects).where(and(eq(businessObjects.modelId, version.businessContextModelId), eq(businessObjects.approvalStatus, "APPROVED"), eq(businessObjects.aiUsageAllowed, true), isNull(businessObjects.deletedAt))), db.select({ id: businessFields.id, businessObjectId: businessFields.businessObjectId, businessName: businessFields.businessName, description: businessFields.description, businessType: businessFields.businessType, fieldRole: businessFields.fieldRole, aggregationRule: businessFields.aggregationRule, filterable: businessFields.filterable, groupable: businessFields.groupable }).from(businessFields).where(and(eq(businessFields.modelId, version.businessContextModelId), eq(businessFields.approvalStatus, "APPROVED"), eq(businessFields.visibleToDashboardCreator, true), eq(businessFields.aiUsageAllowed, true), eq(businessFields.sensitivityClassification, "NONE"), isNull(businessFields.deletedAt))), db.select({ id: businessRelationships.id, sourceObjectId: businessRelationships.sourceObjectId, targetObjectId: businessRelationships.targetObjectId, cardinality: businessRelationships.cardinality }).from(businessRelationships).where(and(eq(businessRelationships.modelId, version.businessContextModelId), eq(businessRelationships.approvalStatus, "APPROVED"), eq(businessRelationships.validationStatus, "VALID"), isNull(businessRelationships.deletedAt))), db.select({ id: kpiDefinitions.id, name: kpiDefinitions.name, description: kpiDefinitions.description, businessQuestion: kpiDefinitions.businessQuestion, measureType: kpiDefinitions.measureType, unit: kpiDefinitions.unit, recommendedVisualization: kpiDefinitions.recommendedVisualization, targetValue: kpiDefinitions.targetValue, status: kpiDefinitions.status, version: kpiDefinitions.version }).from(kpiDefinitions).where(and(eq(kpiDefinitions.modelId, version.businessContextModelId), inArray(kpiDefinitions.status, ["APPROVED", "CERTIFIED"]), isNull(kpiDefinitions.deletedAt))), db.select({ id: dashboardBlocks.id, title: dashboardBlocks.title, blockType: dashboardBlocks.blockType, kpiId: dashboardBlocks.kpiId, dimensionFieldId: dashboardBlocks.dimensionFieldId, visualizationType: dashboardBlocks.visualizationType }).from(dashboardBlocks).where(eq(dashboardBlocks.dashboardVersionId, version.id))]);
  if (request.dashboardBlockId && !blocks.some((block) => block.id === request.dashboardBlockId)) throw new HttpError(404, "Dashboard block not found", "NOT_FOUND");
  const context = { dashboard: { name: dashboard.name, description: dashboard.description, businessObjective: version.businessObjective, targetAudience: version.targetAudience, businessQuestions: JSON.parse(version.businessQuestionsJson) }, request, objects, fields, relationships, kpis, existingBlocks: blocks, security: { publishedContextOnly: true, approvedKpisOnly: true, noCredentials: true, noRowData: true } };
  const config = aiConfig(); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 30_000); let responseJson: unknown;
  try { const response = await fetch(`${config.baseUrl}/chat/completions`, { method: "POST", signal: controller.signal, headers: { "content-type": "application/json", authorization: `Bearer ${config.apiKey}` }, body: JSON.stringify({ model: config.model, temperature: 0.2, response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a governed dashboard design assistant. Recommend only IDs present in the provided JSON. Never invent KPIs, fields, relationships, SQL, or data. Return exactly one JSON object matching the requested keys and always set requiresConfirmation to true." }, { role: "user", content: JSON.stringify(context) }] }) }); const body = await response.json() as { choices?: Array<{ message?: { content?: string } }>; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || "AI provider request failed"); responseJson = safeJson(body.choices?.[0]?.message?.content || ""); } catch (error) { throw new HttpError(502, error instanceof Error && error.name === "AbortError" ? "AI request timed out" : "AI recommendation could not be generated", "AI_REQUEST_FAILED"); } finally { clearTimeout(timeout); }
  const parsed = dashboardRecommendationSchema.parse(responseJson); const allowedKpis = new Set(kpis.map((item) => item.id)); const allowedFields = new Set(fields.map((item) => item.id)); if (parsed.kpiId && !allowedKpis.has(parsed.kpiId)) throw new HttpError(422, "AI recommended an unauthorized KPI", "AI_KPI_REJECTED"); if (parsed.dimensionFieldId && !allowedFields.has(parsed.dimensionFieldId)) throw new HttpError(422, "AI recommended an unauthorized field", "AI_FIELD_REJECTED"); const dimension = parsed.dimensionFieldId ? fields.find((item) => item.id === parsed.dimensionFieldId) : undefined; const kpi = parsed.kpiId ? kpis.find((item) => item.id === parsed.kpiId) : undefined; const compatibility = parsed.visualizationType ? validateVisualization({ blockType: request.dashboardBlockId ? blocks.find((item) => item.id === request.dashboardBlockId)?.blockType || "KPI_CARD" : "KPI_CARD", visualizationType: parsed.visualizationType, dimensionType: dimension?.businessType, hasTarget: Boolean(kpi?.targetValue), kpiMeasureType: kpi?.measureType }) : []; if (compatibility.some((item) => item.severity === "ERROR")) throw new HttpError(422, "AI recommendation failed deterministic visualization validation", "AI_COMPATIBILITY_REJECTED");
  const id = randomUUID(); await db.insert(dashboardAiRecommendations).values({ id, dashboardVersionId: version.id, dashboardBlockId: request.dashboardBlockId, recommendationType: parsed.recommendationType, requestJson: JSON.stringify(request), contextJson: JSON.stringify(context), responseJson: JSON.stringify({ ...parsed, warnings: [...parsed.warnings, ...compatibility.map((item) => item.message)] }), confidence: Math.round(parsed.confidence * 100), modelProvider: config.provider, modelName: config.model, createdBy: user.id, createdAt: new Date() }); return { id, recommendation: parsed };
}

export async function decideDashboardRecommendation(dashboardId: string, recommendationId: string, decision: "ACCEPT" | "REJECT", modifiedResponse: unknown, user: AuthenticatedUser) {
  const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "Published dashboard is immutable", "IMMUTABLE_VERSION"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentDraftVersionId)).limit(1))[0]; if (!version) throw new HttpError(404, "Dashboard version not found", "NOT_FOUND"); const item = (await db.select().from(dashboardAiRecommendations).where(and(eq(dashboardAiRecommendations.id, recommendationId), eq(dashboardAiRecommendations.dashboardVersionId, dashboard.currentDraftVersionId))).limit(1))[0]; if (!item) throw new HttpError(404, "AI recommendation not found", "NOT_FOUND"); if (item.decision !== "PENDING") throw new HttpError(409, "AI recommendation was already reviewed", "ALREADY_REVIEWED"); const response = dashboardRecommendationSchema.parse(modifiedResponse ?? JSON.parse(item.responseJson)); const now = new Date();
  await db.transaction(async (tx) => { if (decision === "ACCEPT" && item.dashboardBlockId) { const block = (await tx.select().from(dashboardBlocks).where(and(eq(dashboardBlocks.id, item.dashboardBlockId), eq(dashboardBlocks.dashboardVersionId, item.dashboardVersionId))).limit(1))[0]; if (!block) throw new HttpError(404, "Dashboard block not found", "NOT_FOUND"); const kpi = response.kpiId ? (await tx.select().from(kpiDefinitions).where(and(eq(kpiDefinitions.id, response.kpiId), eq(kpiDefinitions.modelId, version.businessContextModelId), inArray(kpiDefinitions.status, ["APPROVED", "CERTIFIED"]))).limit(1))[0] : undefined; await tx.update(dashboardBlocks).set({ title: response.suggestedTitle || block.title, description: response.suggestedDescription || block.description, kpiId: response.kpiId || block.kpiId, kpiVersion: kpi?.version ?? block.kpiVersion, dimensionFieldId: response.dimensionFieldId || block.dimensionFieldId, visualizationType: response.visualizationType || block.visualizationType, validationStatus: "NOT_VALIDATED", previewStatus: "NOT_RUN", updatedBy: user.id, updatedAt: now }).where(eq(dashboardBlocks.id, block.id)); await tx.update(dashboardVersions).set({ revision: version.revision + 1, updatedBy: user.id, updatedAt: now }).where(eq(dashboardVersions.id, version.id)); } await tx.update(dashboardAiRecommendations).set({ responseJson: JSON.stringify(response), decision: decision === "REJECT" ? "REJECTED" : modifiedResponse ? "MODIFIED" : "ACCEPTED", decidedBy: user.id, decidedAt: now }).where(eq(dashboardAiRecommendations.id, recommendationId)); }); return { decision };
}
