import { randomUUID } from "node:crypto";
import { and, asc, desc, eq, inArray, isNull, or } from "drizzle-orm";
import { db } from "@/lib/db";
import { businessContextModels, businessContextModelVersions, businessFields, businessObjects, dashboardAiRecommendations, dashboardBlocks, dashboardGlobalFilters, dashboardLayoutTemplates, dashboardPublications, dashboardReviews, dashboards, dashboardValidationFindings, dashboardVersions, dataSources, kpiDefinitions, users } from "@/lib/db/schema";
import type { AuthenticatedUser } from "@/lib/auth/session";
import { hasPermission } from "@/lib/auth/permissions";
import { HttpError } from "@/lib/http";
import { requireDashboardAccess, requireDashboardDataSource, requireDashboardRole } from "./permissions";
import { canTransitionDashboard, defaultVisualization, validateVisualization, type DashboardFinding } from "./rules";
import { generateBlockQuery } from "./query";
import type { z } from "zod";
import type { blockCreateSchema, dashboardCreateSchema, dashboardUpdateSchema, globalFilterSchema, workflowActionSchema } from "./validation";

type CreateInput = z.infer<typeof dashboardCreateSchema>; type UpdateInput = z.infer<typeof dashboardUpdateSchema>; type BlockInput = z.infer<typeof blockCreateSchema>; type GlobalFilterInput = z.infer<typeof globalFilterSchema>; type WorkflowInput = z.infer<typeof workflowActionSchema>;
const draftStatuses = new Set(["DRAFT", "CHANGES_REQUESTED"]);
const layoutFallback = JSON.stringify({ columns: 12, responsive: "stack" });

export async function listDashboardTemplates() { return db.select().from(dashboardLayoutTemplates).where(eq(dashboardLayoutTemplates.isActive, true)).orderBy(asc(dashboardLayoutTemplates.name)); }
export async function listPublishedContexts(user: AuthenticatedUser) {
  requireDashboardRole(user, "CREATE_DASHBOARD");
  const models = await db.select().from(businessContextModels).where(and(eq(businessContextModels.status, "PUBLISHED"), isNull(businessContextModels.deletedAt))).orderBy(desc(businessContextModels.publishedAt)); const result = [];
  for (const model of models) { try { await requireDashboardDataSource(user, model.dataSourceId); } catch { continue; } const version = (await db.select().from(businessContextModelVersions).where(and(eq(businessContextModelVersions.modelId, model.id), eq(businessContextModelVersions.status, "PUBLISHED"), isNull(businessContextModelVersions.deletedAt))).orderBy(desc(businessContextModelVersions.versionNumber)).limit(1))[0]; if (!version) continue; const [source, objects, kpis] = await Promise.all([db.select({ id: dataSources.id, name: dataSources.name }).from(dataSources).where(eq(dataSources.id, model.dataSourceId)).limit(1), db.select({ id: businessObjects.id }).from(businessObjects).where(and(eq(businessObjects.modelId, model.id), eq(businessObjects.approvalStatus, "APPROVED"), isNull(businessObjects.deletedAt))), db.select({ id: kpiDefinitions.id }).from(kpiDefinitions).where(and(eq(kpiDefinitions.modelId, model.id), inArray(kpiDefinitions.status, ["APPROVED", "CERTIFIED"]), isNull(kpiDefinitions.deletedAt)))]); result.push({ ...model, publishedVersion: version, dataSource: source[0], objectCount: objects.length, kpiCount: kpis.length }); }
  return result;
}

export async function listDashboards(user: AuthenticatedUser) {
  requireDashboardRole(user, "VIEW_DASHBOARD"); const rows = await db.select().from(dashboards).where(isNull(dashboards.archivedAt)).orderBy(desc(dashboards.updatedAt));
  return user.role === "ADMIN" ? rows : rows.filter((item) => item.ownerUserId === user.id || item.visibility !== "PRIVATE" || item.status === "PUBLISHED");
}

export async function createDashboard(input: CreateInput, user: AuthenticatedUser) {
  requireDashboardRole(user, "CREATE_DASHBOARD");
  const model = (await db.select().from(businessContextModels).where(and(eq(businessContextModels.id, input.businessContextModelId), eq(businessContextModels.status, "PUBLISHED"), isNull(businessContextModels.deletedAt))).limit(1))[0]; if (!model) throw new HttpError(400, "Select a published Business Context", "CONTEXT_NOT_PUBLISHED");
  const contextVersion = (await db.select().from(businessContextModelVersions).where(and(eq(businessContextModelVersions.id, input.businessContextVersionId), eq(businessContextModelVersions.modelId, model.id), eq(businessContextModelVersions.status, "PUBLISHED"), isNull(businessContextModelVersions.deletedAt))).limit(1))[0]; if (!contextVersion) throw new HttpError(400, "The selected published Business Context version is unavailable", "CONTEXT_VERSION_INVALID");
  await requireDashboardDataSource(user, model.dataSourceId); const template = (await db.select().from(dashboardLayoutTemplates).where(and(eq(dashboardLayoutTemplates.id, input.layoutTemplateId), eq(dashboardLayoutTemplates.isActive, true))).limit(1))[0]; if (!template) throw new HttpError(400, "Layout template not found", "LAYOUT_NOT_FOUND");
  const dashboardId = randomUUID(); const versionId = randomUUID(); const now = new Date();
  await db.transaction(async (tx) => { await tx.insert(dashboards).values({ id: dashboardId, name: input.name, description: input.description, category: input.category, ownerUserId: user.id, businessOwnerUserId: input.businessOwnerUserId, currentDraftVersionId: versionId, status: "DRAFT", createdBy: user.id, updatedBy: user.id, createdAt: now, updatedAt: now }); await tx.insert(dashboardVersions).values({ id: versionId, dashboardId, versionNumber: 1, businessObjective: input.businessObjective, targetAudience: input.targetAudience, businessQuestionsJson: JSON.stringify(input.businessQuestions), refreshExpectation: input.refreshExpectation, defaultDateRange: input.defaultDateRange, tagsJson: JSON.stringify(input.tags), businessContextModelId: model.id, businessContextVersionId: contextVersion.id, dataSourceId: model.dataSourceId, layoutTemplateId: template.id, layoutJson: template.definitionJson || layoutFallback, status: "DRAFT", createdBy: user.id, updatedBy: user.id, createdAt: now, updatedAt: now }); });
  return { dashboardId, versionId };
}

export async function getDashboardWorkspace(id: string, user: AuthenticatedUser) {
  const dashboard = await requireDashboardAccess(user, id, "VIEW"); const versionId = dashboard.currentDraftVersionId || dashboard.currentPublishedVersionId; if (!versionId) throw new HttpError(409, "Dashboard has no active version", "VERSION_NOT_FOUND"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, versionId)).limit(1))[0]; if (!version) throw new HttpError(404, "Dashboard version not found", "NOT_FOUND");
  const [blocks, filters, findings, recommendations, reviews, model, contextVersion, source, kpis, fields, objects, templates, ownerRows] = await Promise.all([db.select().from(dashboardBlocks).where(eq(dashboardBlocks.dashboardVersionId, version.id)).orderBy(asc(dashboardBlocks.sortOrder)), db.select().from(dashboardGlobalFilters).where(eq(dashboardGlobalFilters.dashboardVersionId, version.id)), db.select().from(dashboardValidationFindings).where(eq(dashboardValidationFindings.dashboardVersionId, version.id)), db.select().from(dashboardAiRecommendations).where(eq(dashboardAiRecommendations.dashboardVersionId, version.id)).orderBy(desc(dashboardAiRecommendations.createdAt)), db.select().from(dashboardReviews).where(eq(dashboardReviews.dashboardVersionId, version.id)).orderBy(desc(dashboardReviews.createdAt)), db.select().from(businessContextModels).where(eq(businessContextModels.id, version.businessContextModelId)).limit(1), db.select().from(businessContextModelVersions).where(eq(businessContextModelVersions.id, version.businessContextVersionId)).limit(1), db.select({ id: dataSources.id, name: dataSources.name, environment: dataSources.environment }).from(dataSources).where(eq(dataSources.id, version.dataSourceId)).limit(1), db.select().from(kpiDefinitions).where(and(eq(kpiDefinitions.modelId, version.businessContextModelId), inArray(kpiDefinitions.status, ["APPROVED", "CERTIFIED"]), isNull(kpiDefinitions.deletedAt))), db.select().from(businessFields).where(and(eq(businessFields.modelId, version.businessContextModelId), eq(businessFields.approvalStatus, "APPROVED"), eq(businessFields.visibleToDashboardCreator, true), isNull(businessFields.deletedAt))), db.select().from(businessObjects).where(and(eq(businessObjects.modelId, version.businessContextModelId), eq(businessObjects.approvalStatus, "APPROVED"), isNull(businessObjects.deletedAt))), listDashboardTemplates(), db.select({ id: users.id, fullName: users.fullName }).from(users).where(eq(users.status, "ACTIVE"))]);
  return { dashboard, version, blocks, filters, findings, recommendations, reviews, model: model[0], contextVersion: contextVersion[0], dataSource: source[0], kpis, fields, objects, templates, users: ownerRows, permissions: { canEdit: hasPermission(user.role, "EDIT_DASHBOARD") && draftStatuses.has(version.status) && (user.role === "ADMIN" || dashboard.ownerUserId === user.id), canReview: hasPermission(user.role, "REVIEW_DASHBOARD"), canPublish: hasPermission(user.role, "PUBLISH_DASHBOARD"), canUseAi: hasPermission(user.role, "USE_COPILOT") && dashboard.aiCopilotAllowed } };
}

export async function updateDashboardDraft(dashboardId: string, input: UpdateInput, user: AuthenticatedUser) {
  const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "Published dashboards require a new draft version", "IMMUTABLE_VERSION"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentDraftVersionId)).limit(1))[0]; if (!version || !draftStatuses.has(version.status)) throw new HttpError(409, "This dashboard version is immutable", "IMMUTABLE_VERSION"); if (version.revision !== input.expectedRevision) throw new HttpError(409, "This draft was changed by another session. Reload before saving.", "STALE_VERSION");
  const now = new Date(); const versionChanges = { businessObjective: input.businessObjective, targetAudience: input.targetAudience, businessQuestionsJson: input.businessQuestions ? JSON.stringify(input.businessQuestions) : undefined, refreshExpectation: input.refreshExpectation, defaultDateRange: input.defaultDateRange, tagsJson: input.tags ? JSON.stringify(input.tags) : undefined, layoutTemplateId: input.layoutTemplateId, revision: version.revision + 1, updatedAt: now, updatedBy: user.id }; await db.transaction(async (tx) => { await tx.update(dashboards).set({ name: input.name, description: input.description, category: input.category, updatedAt: now, updatedBy: user.id }).where(eq(dashboards.id, dashboardId)); await tx.update(dashboardVersions).set(versionChanges).where(and(eq(dashboardVersions.id, version.id), eq(dashboardVersions.revision, input.expectedRevision))); }); return { revision: version.revision + 1, savedAt: now };
}

export async function addDashboardBlock(dashboardId: string, input: BlockInput, user: AuthenticatedUser) {
  const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "Create a draft version before adding blocks", "IMMUTABLE_VERSION"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentDraftVersionId)).limit(1))[0]; if (!version || !draftStatuses.has(version.status)) throw new HttpError(409, "Dashboard version is immutable", "IMMUTABLE_VERSION"); let kpiVersion: number | undefined;
  if (input.kpiId) { const kpi = (await db.select().from(kpiDefinitions).where(and(eq(kpiDefinitions.id, input.kpiId), eq(kpiDefinitions.modelId, version.businessContextModelId), inArray(kpiDefinitions.status, ["APPROVED", "CERTIFIED"]), isNull(kpiDefinitions.deletedAt))).limit(1))[0]; if (!kpi) throw new HttpError(400, "KPI is not approved or compatible with this Business Context", "KPI_NOT_ALLOWED"); kpiVersion = kpi.version; }
  if (input.dimensionFieldId) { const field = (await db.select().from(businessFields).where(and(eq(businessFields.id, input.dimensionFieldId), eq(businessFields.modelId, version.businessContextModelId), eq(businessFields.approvalStatus, "APPROVED"), eq(businessFields.visibleToDashboardCreator, true), isNull(businessFields.deletedAt))).limit(1))[0]; if (!field) throw new HttpError(400, "Dimension is not published for dashboard use", "DIMENSION_NOT_ALLOWED"); }
  const now = new Date(); const id = randomUUID(); await db.insert(dashboardBlocks).values({ id, dashboardVersionId: version.id, blockType: input.blockType, title: input.title, description: input.description, businessQuestion: input.businessQuestion, intendedAudience: input.intendedAudience, decisionSupported: input.decisionSupported, kpiId: input.kpiId, kpiVersion, dimensionFieldId: input.dimensionFieldId, visualizationType: input.visualizationType || defaultVisualization(input.blockType), filtersJson: JSON.stringify(input.filters), visualizationConfigJson: JSON.stringify(input.visualizationConfig), formattingConfigJson: JSON.stringify(input.formattingConfig), positionJson: JSON.stringify(input.position), isHidden: input.isHidden, isLocked: input.isLocked, sortOrder: input.position.y * 12 + input.position.x, createdBy: user.id, updatedBy: user.id, createdAt: now, updatedAt: now }); await db.update(dashboardVersions).set({ revision: version.revision + 1, updatedAt: now, updatedBy: user.id }).where(eq(dashboardVersions.id, version.id)); return { id };
}

export async function updateDashboardBlock(dashboardId: string, blockId: string, input: Partial<BlockInput> & { expectedRevision: number }, user: AuthenticatedUser) {
  const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "Published dashboards are immutable", "IMMUTABLE_VERSION"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentDraftVersionId)).limit(1))[0]; if (!version || version.revision !== input.expectedRevision) throw new HttpError(409, "This draft changed in another session", "STALE_VERSION"); const block = (await db.select().from(dashboardBlocks).where(and(eq(dashboardBlocks.id, blockId), eq(dashboardBlocks.dashboardVersionId, version.id))).limit(1))[0]; if (!block) throw new HttpError(404, "Block not found", "NOT_FOUND"); let kpiVersion = block.kpiVersion; if (input.kpiId) { const kpi = (await db.select().from(kpiDefinitions).where(and(eq(kpiDefinitions.id, input.kpiId), eq(kpiDefinitions.modelId, version.businessContextModelId), inArray(kpiDefinitions.status, ["APPROVED", "CERTIFIED"]))).limit(1))[0]; if (!kpi) throw new HttpError(400, "KPI is not compatible", "KPI_NOT_ALLOWED"); kpiVersion = kpi.version; }
  const now = new Date(); await db.transaction(async (tx) => { await tx.update(dashboardBlocks).set({ blockType: input.blockType, title: input.title, description: input.description, businessQuestion: input.businessQuestion, intendedAudience: input.intendedAudience, decisionSupported: input.decisionSupported, kpiId: input.kpiId, kpiVersion, dimensionFieldId: input.dimensionFieldId, visualizationType: input.visualizationType, filtersJson: input.filters ? JSON.stringify(input.filters) : undefined, visualizationConfigJson: input.visualizationConfig ? JSON.stringify(input.visualizationConfig) : undefined, formattingConfigJson: input.formattingConfig ? JSON.stringify(input.formattingConfig) : undefined, positionJson: input.position ? JSON.stringify(input.position) : undefined, isHidden: input.isHidden, isLocked: input.isLocked, validationStatus: "NOT_VALIDATED", previewStatus: "NOT_RUN", updatedBy: user.id, updatedAt: now }).where(eq(dashboardBlocks.id, block.id)); await tx.update(dashboardVersions).set({ revision: version.revision + 1, updatedBy: user.id, updatedAt: now }).where(and(eq(dashboardVersions.id, version.id), eq(dashboardVersions.revision, input.expectedRevision))); }); return { revision: version.revision + 1 };
}

export async function removeDashboardBlock(dashboardId: string, blockId: string, user: AuthenticatedUser) { const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "Published dashboards are immutable", "IMMUTABLE_VERSION"); const block = (await db.select().from(dashboardBlocks).where(and(eq(dashboardBlocks.id, blockId), eq(dashboardBlocks.dashboardVersionId, dashboard.currentDraftVersionId))).limit(1))[0]; if (!block) throw new HttpError(404, "Block not found", "NOT_FOUND"); await db.delete(dashboardBlocks).where(eq(dashboardBlocks.id, blockId)); }
export async function addGlobalFilter(dashboardId: string, input: GlobalFilterInput, user: AuthenticatedUser) { const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "Published dashboards are immutable", "IMMUTABLE_VERSION"); const field = (await db.select().from(businessFields).where(and(eq(businessFields.id, input.businessFieldId), eq(businessFields.filterable, true), eq(businessFields.approvalStatus, "APPROVED"), eq(businessFields.visibleToDashboardCreator, true))).limit(1))[0]; if (!field) throw new HttpError(400, "Filter field is not allowed", "FILTER_NOT_ALLOWED"); const now = new Date(); const id = randomUUID(); await db.insert(dashboardGlobalFilters).values({ id, dashboardVersionId: dashboard.currentDraftVersionId, name: input.name, businessFieldId: input.businessFieldId, filterType: input.filterType, defaultValueJson: JSON.stringify(input.defaultValue ?? null), allowedValuesJson: JSON.stringify(input.allowedValues ?? []), appliesToBlockIdsJson: JSON.stringify(input.appliesToBlockIds), isRequired: input.isRequired, isVisible: input.isVisible, runtimeEditable: input.runtimeEditable, securityEnforced: input.securityEnforced, createdBy: user.id, updatedBy: user.id, createdAt: now, updatedAt: now }); return { id }; }

export async function validateDashboard(dashboardId: string, user: AuthenticatedUser) {
  const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT"); if (!dashboard.currentDraftVersionId) throw new HttpError(409, "No draft version to validate", "VERSION_NOT_FOUND"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentDraftVersionId)).limit(1))[0]; const blocks = await db.select().from(dashboardBlocks).where(eq(dashboardBlocks.dashboardVersionId, version.id)); const findings: DashboardFinding[] = [];
  if (!version.businessObjective.trim()) findings.push({ category: "CONFIGURATION", severity: "ERROR", code: "OBJECTIVE_REQUIRED", message: "Dashboard business objective is required." }); if (!blocks.length) findings.push({ category: "CONFIGURATION", severity: "ERROR", code: "BLOCK_REQUIRED", message: "Add at least one dashboard block." }); if (blocks.length > 20) findings.push({ category: "QUALITY", severity: "WARNING", code: "TOO_MANY_BLOCKS", message: "More than 20 blocks may reduce dashboard clarity." }); const titles = new Set<string>(); const kpis = new Set<string>();
  for (const block of blocks) { if (titles.has(block.title.toLowerCase())) findings.push({ category: "QUALITY", severity: "WARNING", code: "DUPLICATE_TITLE", message: `Duplicate block title: ${block.title}`, dashboardBlockId: block.id }); titles.add(block.title.toLowerCase()); if (block.kpiId && kpis.has(block.kpiId)) findings.push({ category: "QUALITY", severity: "WARNING", code: "DUPLICATE_KPI", message: "The same KPI appears in multiple blocks.", dashboardBlockId: block.id }); if (block.kpiId) kpis.add(block.kpiId); if (!block.description) findings.push({ category: "QUALITY", severity: "WARNING", code: "BLOCK_DESCRIPTION_MISSING", message: "Explain what this block shows.", dashboardBlockId: block.id }); const field = block.dimensionFieldId ? (await db.select().from(businessFields).where(eq(businessFields.id, block.dimensionFieldId)).limit(1))[0] : undefined; const kpi = block.kpiId ? (await db.select().from(kpiDefinitions).where(eq(kpiDefinitions.id, block.kpiId)).limit(1))[0] : undefined; findings.push(...validateVisualization({ blockType: block.blockType, visualizationType: block.visualizationType, dimensionType: field?.businessType, categoryLimit: Number((JSON.parse(block.visualizationConfigJson || "{}") as { categoryLimit?: number }).categoryLimit ?? 10), hasTarget: Boolean(kpi?.targetValue), kpiMeasureType: kpi?.measureType }).map((item) => ({ ...item, dashboardBlockId: block.id }))); try { const generated = await generateBlockQuery(block, version, 100); await db.update(dashboardBlocks).set({ queryPlanJson: JSON.stringify(generated.plan), generatedSql: generated.sql, queryFingerprint: generated.fingerprint, bindParametersJson: JSON.stringify(Object.keys(generated.binds)), validationStatus: "PASSED", updatedAt: new Date(), updatedBy: user.id }).where(eq(dashboardBlocks.id, block.id)); } catch (error) { findings.push({ category: "QUERY", severity: "ERROR", code: "QUERY_PLAN_INVALID", message: error instanceof Error ? error.message : "Query plan generation failed", suggestedCorrection: "Review KPI, dimension, filters, and published relationships.", dashboardBlockId: block.id }); await db.update(dashboardBlocks).set({ validationStatus: "FAILED", updatedAt: new Date(), updatedBy: user.id }).where(eq(dashboardBlocks.id, block.id)); } }
  if (!findings.length) findings.push({ category: "QUALITY", severity: "INFO", code: "DASHBOARD_VALID", message: "Dashboard passed all validation rules." }); await db.delete(dashboardValidationFindings).where(eq(dashboardValidationFindings.dashboardVersionId, version.id)); const now = new Date(); await db.insert(dashboardValidationFindings).values(findings.map((item) => ({ id: randomUUID(), dashboardVersionId: version.id, ...item, createdAt: now }))); const outcome = findings.some((item) => item.severity === "ERROR") ? "FAILED" : findings.some((item) => item.severity === "WARNING") ? "PASSED_WITH_WARNING" : "PASSED"; return { outcome, findings };
}

export async function transitionDashboard(dashboardId: string, input: WorkflowInput, user: AuthenticatedUser) {
  const mode = input.action === "APPROVE" || input.action === "START_REVIEW" || input.action === "REQUEST_CHANGES" ? "REVIEW" : input.action === "PUBLISH" || input.action === "UNPUBLISH" || input.action === "ARCHIVE" ? "PUBLISH" : "EDIT"; const dashboard = await requireDashboardAccess(user, dashboardId, mode); const versionId = dashboard.currentDraftVersionId || dashboard.currentPublishedVersionId; if (!versionId) throw new HttpError(409, "Dashboard version not found", "VERSION_NOT_FOUND"); const version = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, versionId)).limit(1))[0]; const now = new Date();
  if (input.action === "CREATE_VERSION") return createDashboardVersion(dashboardId, user);
  const target = ({ SUBMIT: "READY_FOR_REVIEW", START_REVIEW: "IN_REVIEW", APPROVE: "APPROVED", REQUEST_CHANGES: "CHANGES_REQUESTED", PUBLISH: "PUBLISHED", UNPUBLISH: "UNPUBLISHED", ARCHIVE: "ARCHIVED" } as const)[input.action]; if (!canTransitionDashboard(version.status, target) && !canTransitionDashboard(dashboard.status, target)) throw new HttpError(409, `Cannot transition ${version.status} to ${target}`, "INVALID_TRANSITION");
  if (["REQUEST_CHANGES"].includes(input.action) && !input.comment) throw new HttpError(400, "A review comment is required", "COMMENT_REQUIRED"); if (input.action === "SUBMIT" || input.action === "PUBLISH") { const validation = await validateDashboard(dashboardId, user); if (validation.findings.some((item) => item.severity === "ERROR")) throw new HttpError(409, "Resolve dashboard validation errors before continuing", "VALIDATION_FAILED"); }
  await db.transaction(async (tx) => { await tx.update(dashboardVersions).set({ status: target === "ARCHIVED" || target === "UNPUBLISHED" ? version.status : target as typeof version.status, submittedAt: input.action === "SUBMIT" ? now : version.submittedAt, submittedBy: input.action === "SUBMIT" ? user.id : version.submittedBy, approvedAt: input.action === "APPROVE" ? now : version.approvedAt, approvedBy: input.action === "APPROVE" ? user.id : version.approvedBy, publishedAt: input.action === "PUBLISH" ? now : version.publishedAt, publishedBy: input.action === "PUBLISH" ? user.id : version.publishedBy, updatedAt: now, updatedBy: user.id }).where(eq(dashboardVersions.id, version.id)); await tx.update(dashboards).set({ status: target as typeof dashboard.status, visibility: input.visibility, exportAllowed: input.exportAllowed, aiCopilotAllowed: input.aiCopilotAllowed, currentPublishedVersionId: input.action === "PUBLISH" ? version.id : dashboard.currentPublishedVersionId, currentDraftVersionId: input.action === "PUBLISH" ? null : dashboard.currentDraftVersionId, archivedAt: input.action === "ARCHIVE" ? now : dashboard.archivedAt, updatedAt: now, updatedBy: user.id }).where(eq(dashboards.id, dashboard.id)); await tx.insert(dashboardReviews).values({ id: randomUUID(), dashboardVersionId: version.id, action: input.action === "SUBMIT" ? "SUBMIT" : input.action === "START_REVIEW" ? "COMMENT" : input.action === "APPROVE" ? "APPROVE" : input.action === "REQUEST_CHANGES" ? "REQUEST_CHANGES" : "COMMENT", comment: input.comment, reviewerId: user.id, createdAt: now }); if (input.action === "PUBLISH") { const blocks = await tx.select().from(dashboardBlocks).where(eq(dashboardBlocks.dashboardVersionId, version.id)); const filters = await tx.select().from(dashboardGlobalFilters).where(eq(dashboardGlobalFilters.dashboardVersionId, version.id)); await tx.insert(dashboardPublications).values({ id: randomUUID(), dashboardId, dashboardVersionId: version.id, snapshotJson: JSON.stringify({ dashboard, version: { ...version, status: "PUBLISHED" }, blocks, filters }), visibility: input.visibility ?? dashboard.visibility, allowedRolesJson: JSON.stringify(input.allowedRoles ?? ["VIEWER", "DASHBOARD_CREATOR"]), exportAllowed: input.exportAllowed ?? false, aiCopilotAllowed: input.aiCopilotAllowed ?? false, publishedBy: user.id, publishedAt: now }); } }); return { status: target };
}

export async function createDashboardVersion(dashboardId: string, user: AuthenticatedUser) { const dashboard = await requireDashboardAccess(user, dashboardId, "EDIT").catch(async () => requireDashboardAccess(user, dashboardId, "PUBLISH")); if (dashboard.currentDraftVersionId) throw new HttpError(409, "A draft version already exists", "DRAFT_EXISTS"); if (!dashboard.currentPublishedVersionId) throw new HttpError(409, "No published version to clone", "VERSION_NOT_FOUND"); const source = (await db.select().from(dashboardVersions).where(eq(dashboardVersions.id, dashboard.currentPublishedVersionId)).limit(1))[0]; const sourceBlocks = await db.select().from(dashboardBlocks).where(eq(dashboardBlocks.dashboardVersionId, source.id)); const sourceFilters = await db.select().from(dashboardGlobalFilters).where(eq(dashboardGlobalFilters.dashboardVersionId, source.id)); const id = randomUUID(); const now = new Date(); await db.transaction(async (tx) => { await tx.insert(dashboardVersions).values({ ...source, id, versionNumber: source.versionNumber + 1, status: "DRAFT", revision: 1, submittedAt: null, submittedBy: null, approvedAt: null, approvedBy: null, publishedAt: null, publishedBy: null, createdAt: now, updatedAt: now, createdBy: user.id, updatedBy: user.id }); if (sourceBlocks.length) await tx.insert(dashboardBlocks).values(sourceBlocks.map((block) => ({ ...block, id: randomUUID(), dashboardVersionId: id, validationStatus: "NOT_VALIDATED" as const, previewStatus: "NOT_RUN" as const, previewJson: null, previewedAt: null, createdAt: now, updatedAt: now, createdBy: user.id, updatedBy: user.id }))); if (sourceFilters.length) await tx.insert(dashboardGlobalFilters).values(sourceFilters.map((filter) => ({ ...filter, id: randomUUID(), dashboardVersionId: id, createdAt: now, updatedAt: now, createdBy: user.id, updatedBy: user.id }))); await tx.update(dashboards).set({ currentDraftVersionId: id, status: "DRAFT", updatedAt: now, updatedBy: user.id }).where(eq(dashboards.id, dashboardId)); }); return { versionId: id, versionNumber: source.versionNumber + 1 };
}
