import { z } from "zod";
import { dashboardBlockTypeValues, dashboardVisualizationValues } from "../db/schema";

const uuid = z.string().uuid();
const stringArray = z.array(z.string().trim().min(1).max(500)).max(30);
export const dashboardCreateSchema = z.object({ name: z.string().trim().min(2).max(190), description: z.string().trim().max(4000).optional(), category: z.string().trim().min(2).max(80), businessObjective: z.string().trim().min(5).max(4000), targetAudience: z.string().trim().min(2).max(500), businessQuestions: stringArray.min(1), refreshExpectation: z.string().trim().min(2).max(120), defaultDateRange: z.string().trim().min(2).max(80), tags: z.array(z.string().trim().min(1).max(80)).max(30).default([]), businessOwnerUserId: uuid.optional(), businessContextModelId: uuid, businessContextVersionId: uuid, layoutTemplateId: uuid }).strict();
export const dashboardUpdateSchema = z.object({ name: z.string().trim().min(2).max(190).optional(), description: z.string().trim().max(4000).nullable().optional(), category: z.string().trim().min(2).max(80).optional(), businessObjective: z.string().trim().min(5).max(4000).optional(), targetAudience: z.string().trim().min(2).max(500).optional(), businessQuestions: stringArray.min(1).optional(), refreshExpectation: z.string().trim().min(2).max(120).optional(), defaultDateRange: z.string().trim().min(2).max(80).optional(), tags: z.array(z.string().trim().min(1).max(80)).max(30).optional(), layoutTemplateId: uuid.optional(), expectedRevision: z.number().int().min(1) }).strict();
export const filterSchema = z.object({ businessFieldId: uuid, operator: z.enum(["EQ", "NE", "IN", "NOT_IN", "GT", "GTE", "LT", "LTE", "BETWEEN", "IS_NULL", "IS_NOT_NULL"]), values: z.array(z.union([z.string().max(1000), z.number().finite(), z.boolean(), z.null()])).max(100).default([]) }).strict();
export const queryPlanSchema = z.object({ businessContextVersionId: uuid, dataSourceId: uuid, measure: z.object({ kpiId: uuid, kpiVersion: z.number().int().min(1) }).strict(), dimensions: z.array(z.object({ businessFieldId: uuid, granularity: z.enum(["NONE", "DAY", "WEEK", "MONTH", "QUARTER", "YEAR"]).default("NONE") }).strict()).max(3), filters: z.array(filterSchema).max(20), sort: z.array(z.object({ fieldId: uuid, direction: z.enum(["ASC", "DESC"]) }).strict()).max(5), limit: z.number().int().min(1).max(500), relationshipPathIds: z.array(uuid).max(20) }).strict();
export const blockCreateSchema = z.object({ blockType: z.enum(dashboardBlockTypeValues), title: z.string().trim().min(2).max(190), description: z.string().trim().max(4000).optional(), businessQuestion: z.string().trim().max(4000).optional(), intendedAudience: z.string().trim().max(500).optional(), decisionSupported: z.string().trim().max(4000).optional(), kpiId: uuid.optional(), dimensionFieldId: uuid.optional(), visualizationType: z.enum(dashboardVisualizationValues), filters: z.array(filterSchema).max(20).default([]), visualizationConfig: z.record(z.string(), z.unknown()).default({}), formattingConfig: z.record(z.string(), z.unknown()).default({}), position: z.object({ x: z.number().int().min(0).max(11), y: z.number().int().min(0).max(1000), w: z.number().int().min(1).max(12), h: z.number().int().min(1).max(12) }).strict(), isHidden: z.boolean().default(false), isLocked: z.boolean().default(false) }).strict();
export const blockUpdateSchema = blockCreateSchema.partial().extend({ expectedRevision: z.number().int().min(1) }).strict();
export const globalFilterSchema = z.object({ name: z.string().trim().min(2).max(160), businessFieldId: uuid, filterType: z.enum(["DATE_RANGE", "SINGLE_SELECT", "MULTI_SELECT", "NUMERIC_RANGE", "BOOLEAN"]), defaultValue: z.unknown().optional(), allowedValues: z.array(z.unknown()).max(500).optional(), appliesToBlockIds: z.array(uuid).max(100).default([]), isRequired: z.boolean().default(false), isVisible: z.boolean().default(true), runtimeEditable: z.boolean().default(true), securityEnforced: z.boolean().default(false) }).strict();
export const workflowActionSchema = z.object({ action: z.enum(["SUBMIT", "START_REVIEW", "APPROVE", "REJECT", "REQUEST_CHANGES", "PUBLISH", "UNPUBLISH", "ARCHIVE", "CREATE_VERSION"]), comment: z.string().trim().max(4000).optional(), slug: z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(190).optional(), thumbnailUrl: z.string().url().max(2000).nullable().optional(), visibility: z.enum(["PRIVATE", "ROLE", "WORKSPACE"]).optional(), allowedRoles: z.array(z.enum(["ADMIN", "DATA_SOURCE_CREATOR", "DASHBOARD_CREATOR", "VIEWER"])).max(4).optional(), allowedUserIds: z.array(uuid).max(500).optional(), exportAllowed: z.boolean().optional(), aiCopilotAllowed: z.boolean().optional(), underlyingDataAllowed: z.boolean().optional(), drillDownAllowed: z.boolean().optional(), isFeatured: z.boolean().optional() }).strict();
export const aiRequestSchema = z.object({ dashboardBlockId: uuid.optional(), requestType: z.enum(["BLOCK_CONFIGURATION", "KPI", "DIMENSION", "VISUALIZATION", "LAYOUT", "FILTER", "COVERAGE", "REDUNDANCY"]).default("BLOCK_CONFIGURATION"), instruction: z.string().trim().max(1000).optional() }).strict();
export const recommendationDecisionSchema = z.object({ decision: z.enum(["ACCEPT", "REJECT"]), modifiedResponse: z.unknown().optional() }).strict();
