import { createHash, randomUUID } from "node:crypto";
import { and, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/lib/db";
import { dataSourceColumns, dataSourceIndexes, dataSourceRelationships, dataSourceSchemas, dataSources, dataSourceTables, metadataSyncRuns } from "@/lib/db/schema";
import type { AuthenticatedUser } from "@/lib/auth/session";
import type { RequestMeta } from "@/lib/auth/request";
import { HttpError } from "@/lib/http";
import { getDataSource, requireDataSourceAccess } from "./service";
import { discoverMetadata } from "./metadata";
import { suggestSensitivity } from "./masking";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const batches = <T>(items: T[], size = 100) => Array.from({ length: Math.ceil(items.length / size) }, (_, index) => items.slice(index * size, (index + 1) * size));
export async function syncMetadata(dataSourceId: string, syncType: "FULL" | "INCREMENTAL" | "SCHEMA" | "TABLE", user: AuthenticatedUser, meta: RequestMeta, scope: { schemaName?: string; tableId?: string } = {}) {
  await requireDataSourceAccess(user, dataSourceId, "SYNC_METADATA"); const source = await getDataSource(dataSourceId); if (!source) throw new HttpError(404, "Data source not found", "NOT_FOUND");
  const runId = randomUUID(); const startedAt = new Date(); await db.insert(metadataSyncRuns).values({ id: runId, dataSourceId, syncType, status: "RUNNING", progressStep: "Connecting", startedBy: user.id, startedAt, requestId: meta.requestId }); await db.update(dataSources).set({ metadataSyncStatus: "SYNCING" }).where(eq(dataSources.id, dataSourceId));
  try {
    const selectedRows = await db.select().from(dataSourceSchemas).where(and(eq(dataSourceSchemas.dataSourceId, dataSourceId), eq(dataSourceSchemas.isIncluded, true)));
    const configured = JSON.parse(source.allowedSchemas || "[]") as string[]; let selected = selectedRows.length ? selectedRows.map((s) => s.schemaName) : configured;
    if (!selected.length) throw new HttpError(400, "Select at least one schema before synchronization", "SCHEMA_REQUIRED");
    let targetTable: typeof dataSourceTables.$inferSelect | undefined; if (syncType === "SCHEMA") { if (!scope.schemaName || !selected.includes(scope.schemaName)) throw new HttpError(400, "Schema is not included", "INVALID_SCHEMA"); selected = [scope.schemaName]; } if (syncType === "TABLE") { if (!scope.tableId) throw new HttpError(400, "tableId is required", "INVALID_TABLE"); targetTable = (await db.select().from(dataSourceTables).where(and(eq(dataSourceTables.id, scope.tableId), eq(dataSourceTables.dataSourceId, dataSourceId))).limit(1))[0]; if (!targetTable || !selected.includes(targetTable.schemaName)) throw new HttpError(400, "Table is not included", "INVALID_TABLE"); selected = [targetTable.schemaName]; }
    await db.update(metadataSyncRuns).set({ progressStep: "Reading metadata" }).where(eq(metadataSyncRuns.id, runId)); const raw = await discoverMetadata(source, selected); const discovered = targetTable ? { schemas: raw.schemas, tables: raw.tables.filter((t) => t.tableName === targetTable!.tableName), columns: raw.columns.filter((c) => c.tableName === targetTable!.tableName), constraints: raw.constraints.filter((c) => c.tableName === targetTable!.tableName), indexes: raw.indexes.filter((i) => i.tableName === targetTable!.tableName) } : raw;
    const existingTables = await db.select().from(dataSourceTables).where(eq(dataSourceTables.dataSourceId, dataSourceId)); const existingTableKeys = new Set(existingTables.map((t) => `${t.schemaName}.${t.tableName}`)); const existingIds = existingTables.map((t) => t.id); const existingColumns = existingIds.length ? await db.select().from(dataSourceColumns).where(inArray(dataSourceColumns.tableId, existingIds)) : []; const existingColumnKeys = new Set(existingColumns.map((c) => `${c.tableId}.${c.columnName}`)); let newObjects = 0; let updatedObjects = 0;
    const scopedExistingIds = syncType === "FULL" || syncType === "INCREMENTAL" ? existingIds : syncType === "SCHEMA" ? existingTables.filter((t) => t.schemaName === scope.schemaName).map((t) => t.id) : targetTable ? [targetTable.id] : [];
    const scopedExistingKeys = new Set(existingTables.filter((t) => scopedExistingIds.includes(t.id)).map((t) => `${t.schemaName}.${t.tableName}`));
    await db.transaction(async (tx) => {
      await tx.update(metadataSyncRuns).set({ progressStep: "Saving metadata" }).where(eq(metadataSyncRuns.id, runId));
      if (syncType !== "INCREMENTAL") { if (syncType === "FULL") { await tx.update(dataSourceSchemas).set({ status: "MISSING" }).where(and(eq(dataSourceSchemas.dataSourceId, dataSourceId), eq(dataSourceSchemas.isIncluded, true))); await tx.update(dataSourceTables).set({ status: "MISSING" }).where(eq(dataSourceTables.dataSourceId, dataSourceId)); } else if (syncType === "SCHEMA") { await tx.update(dataSourceSchemas).set({ status: "MISSING" }).where(and(eq(dataSourceSchemas.dataSourceId, dataSourceId), eq(dataSourceSchemas.schemaName, scope.schemaName!))); await tx.update(dataSourceTables).set({ status: "MISSING" }).where(and(eq(dataSourceTables.dataSourceId, dataSourceId), eq(dataSourceTables.schemaName, scope.schemaName!))); } else if (targetTable) await tx.update(dataSourceTables).set({ status: "MISSING" }).where(eq(dataSourceTables.id, targetTable.id)); if (scopedExistingIds.length) { await tx.update(dataSourceColumns).set({ status: "MISSING" }).where(inArray(dataSourceColumns.tableId, scopedExistingIds)); await tx.update(dataSourceIndexes).set({ status: "MISSING" }).where(inArray(dataSourceIndexes.tableId, scopedExistingIds)); } }
      const now = new Date();
      for (const schema of discovered.schemas) await tx.insert(dataSourceSchemas).values({ id: randomUUID(), dataSourceId, schemaName: schema.schemaName, tableCount: schema.tableCount, viewCount: schema.viewCount, isIncluded: true, status: "ACTIVE", lastSyncedAt: now, createdAt: now, updatedAt: now }).onDuplicateKeyUpdate({ set: { tableCount: schema.tableCount, viewCount: schema.viewCount, status: "ACTIVE", lastSyncedAt: now, updatedAt: now } });
      const schemaRows = await tx.select().from(dataSourceSchemas).where(eq(dataSourceSchemas.dataSourceId, dataSourceId)); const schemaMap = new Map(schemaRows.map((s) => [s.schemaName, s.id]));
      for (const table of discovered.tables) { const key = `${table.schemaName}.${table.tableName}`; if (existingTableKeys.has(key)) updatedObjects++; else newObjects++; }
      for (const batch of batches(discovered.tables)) await tx.insert(dataSourceTables).values(batch.map((table) => ({ id: randomUUID(), dataSourceId, schemaId: schemaMap.get(table.schemaName), schemaName: table.schemaName, tableName: table.tableName, objectType: table.objectType, description: table.description, estimatedRowCount: table.estimatedRowCount, lastAnalyzedAt: table.lastAnalyzedAt, isPartitioned: table.isPartitioned, isTemporary: table.isTemporary, isIncluded: true, status: "ACTIVE" as const, metadataHash: hash(table), lastSyncedAt: now, createdAt: now, updatedAt: now }))).onDuplicateKeyUpdate({ set: { objectType: sql`VALUES(object_type)`, description: sql`VALUES(description)`, estimatedRowCount: sql`VALUES(estimated_row_count)`, lastAnalyzedAt: sql`VALUES(last_analyzed_at)`, isPartitioned: sql`VALUES(is_partitioned)`, isTemporary: sql`VALUES(is_temporary)`, status: "ACTIVE", metadataHash: sql`VALUES(metadata_hash)`, lastSyncedAt: now, updatedAt: now } });
      const tableRows = await tx.select().from(dataSourceTables).where(eq(dataSourceTables.dataSourceId, dataSourceId)); const tableMap = new Map(tableRows.map((t) => [`${t.schemaName}.${t.tableName}`, t]));
      const pk = new Set(discovered.constraints.filter((c) => c.constraintType === "P").map((c) => `${c.owner}.${c.tableName}.${c.columnName}`)); const fk = new Set(discovered.constraints.filter((c) => c.constraintType === "R").map((c) => `${c.owner}.${c.tableName}.${c.columnName}`));
      const columnValues = discovered.columns.flatMap((column) => { const table = tableMap.get(`${column.schemaName}.${column.tableName}`); if (!table) return []; const key = `${table.id}.${column.columnName}`; if (existingColumnKeys.has(key)) updatedObjects++; else newObjects++; const suggestion = suggestSensitivity(column.columnName); return [{ id: randomUUID(), tableId: table.id, columnName: column.columnName, description: column.description, dataType: column.dataType, dataLength: column.dataLength, numericPrecision: column.numericPrecision, numericScale: column.numericScale, nullable: column.nullable, defaultValue: column.defaultValue, ordinalPosition: column.ordinalPosition, isPrimaryKey: pk.has(`${column.schemaName}.${column.tableName}.${column.columnName}`), isForeignKey: fk.has(`${column.schemaName}.${column.tableName}.${column.columnName}`), sensitivityType: "NONE" as const, suggestedSensitivityType: suggestion, isIncluded: suggestion !== "CREDENTIAL", status: "ACTIVE" as const, metadataHash: hash(column), createdAt: now, updatedAt: now }]; });
      for (const batch of batches(columnValues)) await tx.insert(dataSourceColumns).values(batch).onDuplicateKeyUpdate({ set: { description: sql`VALUES(description)`, dataType: sql`VALUES(data_type)`, dataLength: sql`VALUES(data_length)`, numericPrecision: sql`VALUES(numeric_precision)`, numericScale: sql`VALUES(numeric_scale)`, nullable: sql`VALUES(nullable)`, defaultValue: sql`VALUES(default_value)`, ordinalPosition: sql`VALUES(ordinal_position)`, isPrimaryKey: sql`VALUES(is_primary_key)`, isForeignKey: sql`VALUES(is_foreign_key)`, suggestedSensitivityType: sql`VALUES(suggested_sensitivity_type)`, status: "ACTIVE", metadataHash: sql`VALUES(metadata_hash)`, updatedAt: now } });
      const currentTableIds = tableRows.map((table) => table.id); const columnRows = currentTableIds.length ? await tx.select().from(dataSourceColumns).where(inArray(dataSourceColumns.tableId, currentTableIds)) : []; const columnMap = new Map(columnRows.map((c) => [`${c.tableId}.${c.columnName}`, c.id])); if (syncType === "FULL" || syncType === "INCREMENTAL") await tx.delete(dataSourceRelationships).where(eq(dataSourceRelationships.dataSourceId, dataSourceId)); else if (scopedExistingIds.length) await tx.delete(dataSourceRelationships).where(inArray(dataSourceRelationships.sourceTableId, scopedExistingIds));
      const indexValues = discovered.indexes.flatMap((index) => { const table = tableMap.get(`${index.owner}.${index.tableName}`); return table ? [{ id: randomUUID(), tableId: table.id, indexName: index.indexName, columnName: index.columnName, columnPosition: index.columnPosition, isUnique: index.isUnique, status: "ACTIVE" as const, createdAt: now, updatedAt: now }] : []; });
      for (const batch of batches(indexValues)) await tx.insert(dataSourceIndexes).values(batch).onDuplicateKeyUpdate({ set: { columnPosition: sql`VALUES(column_position)`, isUnique: sql`VALUES(is_unique)`, status: "ACTIVE", updatedAt: now } });
      const relationshipValues = discovered.constraints.filter((c) => c.constraintType === "R" && c.referencedOwner && c.referencedTable && c.referencedColumn).flatMap((relation) => { const from = tableMap.get(`${relation.owner}.${relation.tableName}`); const to = tableMap.get(`${relation.referencedOwner}.${relation.referencedTable}`); return from && to ? [{ id: randomUUID(), dataSourceId, sourceTableId: from.id, sourceColumnId: columnMap.get(`${from.id}.${relation.columnName}`), targetTableId: to.id, targetColumnId: columnMap.get(`${to.id}.${relation.referencedColumn}`), constraintName: relation.constraintName, relationshipType: "MANY_TO_ONE" as const, discoveryMethod: "FOREIGN_KEY" as const, confidenceScore: 100, status: "CONFIRMED" as const, createdAt: now, updatedAt: now }] : []; });
      for (const batch of batches(relationshipValues)) await tx.insert(dataSourceRelationships).values(batch);
      const missingObjects = syncType === "INCREMENTAL" ? 0 : Math.max(0, scopedExistingKeys.size - discovered.tables.filter((t) => scopedExistingKeys.has(`${t.schemaName}.${t.tableName}`)).length); const completedAt = new Date(); const summary = { status: "COMPLETED" as const, progressStep: "Completed", completedAt, durationMs: completedAt.getTime() - startedAt.getTime(), schemasProcessed: discovered.schemas.length, tablesFound: discovered.tables.filter((t) => t.objectType === "TABLE").length, viewsFound: discovered.tables.filter((t) => t.objectType === "VIEW").length, columnsFound: discovered.columns.length, primaryKeysFound: discovered.constraints.filter((c) => c.constraintType === "P").length, foreignKeysFound: discovered.constraints.filter((c) => c.constraintType === "R").length, relationshipsFound: discovered.constraints.filter((c) => c.constraintType === "R").length, newObjects, updatedObjects, missingObjects };
      await tx.update(metadataSyncRuns).set(summary).where(eq(metadataSyncRuns.id, runId)); await tx.update(dataSources).set({ metadataSyncStatus: "SYNCED", lastMetadataSyncAt: completedAt, updatedAt: completedAt, updatedBy: user.id }).where(eq(dataSources.id, dataSourceId));
    });
    return (await db.select().from(metadataSyncRuns).where(eq(metadataSyncRuns.id, runId)).limit(1))[0];
  } catch (error) { const completedAt = new Date(); await db.update(metadataSyncRuns).set({ status: "FAILED", progressStep: "Failed", completedAt, durationMs: completedAt.getTime() - startedAt.getTime(), errorCount: 1, errorSummary: error instanceof Error ? error.message.slice(0, 1000) : "Metadata sync failed" }).where(eq(metadataSyncRuns.id, runId)); await db.update(dataSources).set({ metadataSyncStatus: "FAILED" }).where(eq(dataSources.id, dataSourceId)); throw error; }
}
