import { z } from "zod";
const base = z.object({ name: z.string().trim().min(2).max(160), description: z.string().trim().max(4000).optional(), environment: z.enum(["DEVELOPMENT", "TEST", "UAT", "PRODUCTION"]), status: z.enum(["DRAFT", "ACTIVE", "INACTIVE"]).default("DRAFT"), host: z.string().trim().max(255).default(""), port: z.coerce.number().int().min(1).max(65535).default(1521), connectionMode: z.enum(["SERVICE_NAME", "SID", "CONNECTION_STRING"]), serviceName: z.string().trim().max(255).optional(), sid: z.string().trim().max(255).optional(), connectionString: z.string().trim().max(2000).optional(), username: z.string().trim().min(1).max(255), password: z.string().min(1).max(2048), defaultSchema: z.string().trim().max(128).optional(), allowedSchemas: z.array(z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_$#]*$/).max(128)).max(100).default([]), connectionTimeoutSeconds: z.coerce.number().int().min(1).max(120).default(10), queryTimeoutSeconds: z.coerce.number().int().min(1).max(600).default(30) });
function connectionRules(v: z.infer<typeof base>, ctx: z.RefinementCtx) { if (v.connectionMode !== "CONNECTION_STRING" && !v.host) ctx.addIssue({ code: "custom", path: ["host"], message: "Host is required" }); if (v.connectionMode === "SERVICE_NAME" && !v.serviceName) ctx.addIssue({ code: "custom", path: ["serviceName"], message: "Service name is required" }); if (v.connectionMode === "SID" && !v.sid) ctx.addIssue({ code: "custom", path: ["sid"], message: "SID is required" }); if (v.connectionMode === "CONNECTION_STRING" && !v.connectionString) ctx.addIssue({ code: "custom", path: ["connectionString"], message: "Connection string is required" }); if (v.connectionString && /(password|pwd)\s*=|\/[^@\s]+@/i.test(v.connectionString)) ctx.addIssue({ code: "custom", path: ["connectionString"], message: "Connection string must not contain credentials" }); }
export const dataSourceInputSchema = base.superRefine(connectionRules);
export const dataSourceUpdateSchema = base.partial().extend({ password: z.string().min(1).max(2048).optional() }).strict();
export const schemaSelectionSchema = z.object({ includedSchemas: z.array(z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_$#]*$/)).max(100) });
export const syncRequestSchema = z.object({ syncType: z.enum(["FULL", "INCREMENTAL", "SCHEMA", "TABLE"]).default("FULL"), schemaName: z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_$#]*$/).optional(), tableId: z.string().uuid().optional() }).superRefine((value, ctx) => { if (value.syncType === "SCHEMA" && !value.schemaName) ctx.addIssue({ code: "custom", path: ["schemaName"], message: "schemaName is required" }); if (value.syncType === "TABLE" && !value.tableId) ctx.addIssue({ code: "custom", path: ["tableId"], message: "tableId is required" }); });
export const previewSchema = z.object({ rowLimit: z.coerce.number().int().min(1).max(100).default(20) }).strict();
export const accessGrantSchema = z.object({ dataSourceId: z.string().uuid(), userId: z.string().uuid().optional(), role: z.enum(["ADMIN", "DATA_SOURCE_CREATOR", "DASHBOARD_CREATOR", "VIEWER"]).optional(), permission: z.enum(["VIEW_METADATA", "PREVIEW_DATA", "USE_FOR_DASHBOARD", "EDIT_METADATA", "MANAGE_CONNECTION", "SYNC_METADATA", "MANAGE_BUSINESS_CONTEXT", "PUBLISH_BUSINESS_CONTEXT", "USE_BUSINESS_CONTEXT"]) }).refine((v) => Boolean(v.userId) !== Boolean(v.role), { message: "Choose exactly one user or role" });
