ALTER TABLE `data_source_columns` ADD COLUMN `status` enum('ACTIVE','MISSING','EXCLUDED','ARCHIVED') NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE `data_source_tables` ADD CONSTRAINT `data_source_tables_schema_fk` FOREIGN KEY (`schema_id`) REFERENCES `data_source_schemas` (`id`) ON DELETE SET NULL;
ALTER TABLE `data_source_access` ADD CONSTRAINT `data_source_access_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS `data_source_relationships` (
  `id` varchar(36) NOT NULL, `data_source_id` varchar(36) NOT NULL, `source_table_id` varchar(36) NOT NULL, `source_column_id` varchar(36), `target_table_id` varchar(36) NOT NULL, `target_column_id` varchar(36), `constraint_name` varchar(128), `relationship_type` varchar(40) NOT NULL DEFAULT 'MANY_TO_ONE', `discovery_method` enum('FOREIGN_KEY','NAME_PATTERN','MANUAL') NOT NULL DEFAULT 'FOREIGN_KEY', `confidence_score` int NOT NULL DEFAULT 100, `status` enum('SUGGESTED','CONFIRMED','REJECTED','DISABLED') NOT NULL DEFAULT 'CONFIRMED', `reviewed_by` varchar(36), `reviewed_at` datetime(3), `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `relationships_constraint_uq` (`data_source_id`,`constraint_name`,`source_column_id`), KEY `relationships_source_idx` (`source_table_id`), KEY `relationships_target_idx` (`target_table_id`),
  CONSTRAINT `relationships_data_source_fk` FOREIGN KEY (`data_source_id`) REFERENCES `data_sources` (`id`) ON DELETE CASCADE, CONSTRAINT `relationships_source_table_fk` FOREIGN KEY (`source_table_id`) REFERENCES `data_source_tables` (`id`) ON DELETE CASCADE, CONSTRAINT `relationships_source_column_fk` FOREIGN KEY (`source_column_id`) REFERENCES `data_source_columns` (`id`) ON DELETE SET NULL, CONSTRAINT `relationships_target_table_fk` FOREIGN KEY (`target_table_id`) REFERENCES `data_source_tables` (`id`) ON DELETE CASCADE, CONSTRAINT `relationships_target_column_fk` FOREIGN KEY (`target_column_id`) REFERENCES `data_source_columns` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `metadata_sync_runs` (
  `id` varchar(36) NOT NULL, `data_source_id` varchar(36) NOT NULL, `sync_type` enum('FULL','INCREMENTAL','SCHEMA','TABLE') NOT NULL DEFAULT 'FULL', `status` enum('QUEUED','RUNNING','COMPLETED','PARTIAL','FAILED','CANCELLED') NOT NULL DEFAULT 'QUEUED', `progress_step` varchar(80), `started_by` varchar(36) NOT NULL, `started_at` datetime(3) NOT NULL, `completed_at` datetime(3), `duration_ms` int, `schemas_processed` int NOT NULL DEFAULT 0, `tables_found` int NOT NULL DEFAULT 0, `views_found` int NOT NULL DEFAULT 0, `columns_found` int NOT NULL DEFAULT 0, `primary_keys_found` int NOT NULL DEFAULT 0, `foreign_keys_found` int NOT NULL DEFAULT 0, `relationships_found` int NOT NULL DEFAULT 0, `new_objects` int NOT NULL DEFAULT 0, `updated_objects` int NOT NULL DEFAULT 0, `missing_objects` int NOT NULL DEFAULT 0, `warning_count` int NOT NULL DEFAULT 0, `error_count` int NOT NULL DEFAULT 0, `error_summary` text, `request_id` varchar(36) NOT NULL,
  PRIMARY KEY (`id`), KEY `sync_runs_source_idx` (`data_source_id`), KEY `sync_runs_started_idx` (`started_at`), CONSTRAINT `sync_runs_source_fk` FOREIGN KEY (`data_source_id`) REFERENCES `data_sources` (`id`) ON DELETE CASCADE
);
