import { describe, expect, it } from "vitest";
import { BLOCK_REGISTRY, composeDashboardPlan, dashboardPlanningOutputSchema, evaluateDashboardQuality, fieldInformationScore, scoreBlockSuitability, validateBlockRequirement, validateDatasetRows, type PlanningField, type PlanningMetric } from "../lib/dashboards/planning";

const profile=(values:Partial<PlanningField["profile"]>={})=>({sampleSize:100,nonNullCount:100,nullRatio:0,distinctCount:10,numericCount:0,zeroCount:0,minimum:null,maximum:null,mean:null,standardDeviation:null,sampleValues:[],...values});
const fields:PlanningField[]=[
  {id:"10000000-0000-4000-8000-000000000001",businessName:"State",physicalColumnName:"STATE",businessType:"STATUS",fieldRole:"STATUS_DIMENSION",groupable:true,filterable:true,searchable:false,businessObjectId:"o",profile:profile({distinctCount:4})},
  {id:"10000000-0000-4000-8000-000000000002",businessName:"Machine Description",physicalColumnName:"MCH_CODE_DESCRIPTION",businessType:"TEXT",fieldRole:"DIMENSION",groupable:true,filterable:true,searchable:true,businessObjectId:"o",profile:profile({distinctCount:428})},
  {id:"10000000-0000-4000-8000-000000000003",businessName:"Registration Date",physicalColumnName:"REG_DATE",businessType:"DATE",fieldRole:"DATE_DIMENSION",groupable:true,filterable:true,searchable:false,businessObjectId:"o",profile:profile({distinctCount:90})},
];
const metrics:PlanningMetric[]=[{id:"20000000-0000-4000-8000-000000000001",code:"active_work_orders",name:"Active Work Orders",description:"Open work orders",businessQuestion:"How many work orders are active?",measureType:"COUNT",targetValue:null,defaultDateFieldId:fields[2].id}];

describe("structured dashboard planning",()=>{
  it("defines requirements for every supported generated block",()=>{expect(Object.keys(BLOCK_REGISTRY)).toHaveLength(10);expect(BLOCK_REGISTRY.TREND_CHART.requiresTimeDimension).toBe(true);expect(BLOCK_REGISTRY.FUNNEL.requiresOrderedStages).toBe(true);expect(BLOCK_REGISTRY.PROGRESS_STATUS.requiresTarget).toBe(true);});
  it("rejects unsupported funnel, progress, and trend candidates",()=>{expect(validateBlockRequirement({blockType:"FUNNEL",shape:"STAGE_FUNNEL",measureCount:1,dimensionCount:1,hasTimeDimension:false,hasTarget:false,hasOrderedStages:false,hasExceptionCondition:false}).valid).toBe(false);expect(validateBlockRequirement({blockType:"PROGRESS_STATUS",shape:"ACTUAL_VS_TARGET",measureCount:1,dimensionCount:0,hasTimeDimension:false,hasTarget:false,hasOrderedStages:false,hasExceptionCondition:false}).issues).toContain("A governed target is required");});
  it("uses the documented weighted suitability score and threshold",()=>{const score=scoreBlockSuitability({blockType:"TREND_CHART",businessRelevance:100,dataQuality:80,informationValue:60,visualizationFit:100,actionability:50,audienceFit:80});expect(score.totalScore).toBe(83);});
  it("excludes constant and zero-only fields from planning",()=>{expect(fieldInformationScore({...fields[1],profile:profile({distinctCount:1})})).toBe(0);expect(fieldInformationScore({...fields[1],businessType:"NUMBER",fieldRole:"MEASURE",profile:profile({numericCount:100,zeroCount:100,distinctCount:1,standardDeviation:0})})).toBe(0);});
  it("reuses one metric across multiple dataset shapes and maps existing smart controls",()=>{const plan=composeDashboardPlan({title:"Active Work Order Overview",description:"Operational control",businessObjective:"Control active maintenance workload",targetAudience:"Operational manager",requestedQuestions:["How many work orders are active?"],metrics,fields});expect(new Set(plan.blocks.flatMap(block=>block.metricKey?[block.metricKey]:[]))).toEqual(new Set(["active_work_orders"]));expect(plan.blocks.map(block=>block.datasetShape)).toEqual(expect.arrayContaining(["SINGLE_VALUE","TIME_SERIES","CATEGORY_DISTRIBUTION","CATEGORY_COMPARISON","SUMMARY_RECORDS","NARRATIVE_INPUT"]));expect(plan.blocks.filter(block=>block.type==="KPI_CARD").length/plan.blocks.length).toBeLessThanOrEqual(.4);expect(plan.filters.find(filter=>filter.fieldId===fields[0].id)?.controlType).toBe("MULTI_SELECT");expect(plan.filters.find(filter=>filter.fieldId===fields[1].id)?.controlType).toBe("ASYNC_SEARCHABLE_MULTI_SELECT");});
  it("validates actual result shape and recommends repair",()=>{expect(validateDatasetRows([{DIMENSION_VALUE:"2026-01",KPI_VALUE:10}],"TIME_SERIES")).toMatchObject({valid:false,recommendedAction:"CHANGE_BLOCK_TYPE"});expect(validateDatasetRows([{DIMENSION_VALUE:"Released",KPI_VALUE:5},{DIMENSION_VALUE:"Started",KPI_VALUE:8}],"CATEGORY_DISTRIBUTION")).toMatchObject({valid:true,recommendedAction:"KEEP"});});
  it("blocks quality-gate failures",()=>{const quality=evaluateDashboardQuality([{id:"b1",type:"KPI_CARD",metricKey:"m",position:{x:0,y:0,w:12,h:2},suitabilityScore:80}],[]);expect(quality.passed).toBe(false);expect(quality.issues.map(issue=>issue.code)).toContain("EXCESSIVE_KPI_CARDS");});
  it("validates the SQL-free AI planning contract",()=>{const plan=composeDashboardPlan({title:"Active Work Orders",description:"Overview",businessObjective:"Control work",targetAudience:"Manager",requestedQuestions:["What is happening?"],metrics,fields});const contract={dashboard:{title:plan.title,description:plan.description,businessObjective:plan.businessObjective,audience:plan.audience},businessQuestions:plan.businessQuestions,metrics:plan.metrics.map(metric=>({metricKey:metric.metricKey,kpiId:metric.kpiId})),recommendedFilters:plan.filters.map(filter=>({fieldId:filter.fieldId,controlType:filter.controlType})),blockCandidates:plan.blocks.map(block=>({type:block.type,datasetShape:block.datasetShape,kpiId:block.kpiId,dimensionFieldIds:block.dimensionFieldIds})),selectedBlocks:plan.blocks.map(block=>block.id),layout:{columns:12},filterCompatibility:[],qualityExpectations:{minimumScore:60}};expect(dashboardPlanningOutputSchema.parse(contract)).toBeTruthy();expect(JSON.stringify(contract)).not.toMatch(/\bSELECT\b/i);});
});
