"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { readAiProgressResponse, type AiProgress } from "@/lib/ai/progress-client";
import AiGenerationProgress from "@/components/shared/ai-generation-progress";

type Template={id:string;code:string;name:string;description:string;definitionJson:string};
type Context={id:string;name:string;description:string|null;publishedVersion:{id:string;versionNumber:number};dataSource?:{name:string};objectCount:number;kpiCount:number};

export default function DashboardCreateWizard(){
  const router=useRouter(); const [step,setStep]=useState(1); const [templates,setTemplates]=useState<Template[]>([]); const [contexts,setContexts]=useState<Context[]>([]); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState(""); const [question,setQuestion]=useState(""); const [generationProgress,setGenerationProgress]=useState<AiProgress|null>(null); const [generationElapsed,setGenerationElapsed]=useState(0);
  const [form,setForm]=useState({name:"",description:"",category:"Operations",businessObjective:"",targetAudience:"Operations managers",businessQuestions:[] as string[],refreshExpectation:"On demand",defaultDateRange:"Last 30 days",tags:[] as string[],businessContextModelId:"",businessContextVersionId:"",layoutTemplateId:""});
  const generationActive=submitting&&generationProgress!==null;
  useEffect(()=>{void fetch("/api/dashboards/options").then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setTemplates(body.templates??[]);setContexts(body.contexts??[]);}).catch((reason)=>setError(reason.message)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(!generationActive)return;const started=Date.now();const timer=window.setInterval(()=>setGenerationElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>window.clearInterval(timer);},[generationActive]);
  function addQuestion(){const value=question.trim();if(value&&!form.businessQuestions.includes(value))setForm({...form,businessQuestions:[...form.businessQuestions,value]});setQuestion("");}
  async function submit(path:string){const layoutTemplateId=form.layoutTemplateId||templates[0]?.id;const businessQuestions=form.businessQuestions.length?form.businessQuestions:[form.businessObjective];if(!layoutTemplateId)return setError("No active dashboard layout is available");const generated=path.endsWith("generate");setSubmitting(true);setError("");if(generated){setGenerationElapsed(0);setGenerationProgress({stage:"CONNECTING",label:"Starting dashboard generation",detail:"Opening a live progress connection to the structured dashboard pipeline.",percent:2});}else setGenerationProgress(null);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json",...(generated?{Accept:"text/event-stream"}:{})},body:JSON.stringify({...form,layoutTemplateId,businessQuestions})});const body=generated?await readAiProgressResponse<{previewPath?:string;dashboardId:string}>(response,setGenerationProgress):await response.json();if(!generated&&!response.ok)throw new Error(body.error||"Unable to create dashboard");router.push(generated?(body.previewPath||`/workspace/dashboards/${body.dashboardId}/edit?step=preview`):`/dashboards/${body.dashboardId}`);router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create dashboard");}finally{setSubmitting(false);}}
  const selectedContext=contexts.find((item)=>item.id===form.businessContextModelId);
  const purposeReady=Boolean(form.name.trim()&&form.businessObjective.trim());
  return <main className="workspace-page dashboard-wizard-page">
    <header><p className="eyebrow">GUIDED DASHBOARD BUILDER</p><h1>Create dashboard project</h1><p>Start with the decision you need to support. Technical Oracle details remain governed behind the Business Context.</p></header>
    <nav className="wizard-steps" aria-label="Dashboard setup steps">{["Purpose","Business Context","Layout","Review"].map((label,index)=><button key={label} className={step===index+1?"active":step>index+1?"done":""} onClick={()=>step>index+1&&setStep(index+1)}><span>{step>index+1?"✓":index+1}</span>{label}</button>)}</nav>
    {loading?<div className="insight-loading"><span className="insight-spinner"/><span>Loading published business context…</span></div>:<section className="wizard-card">
      {step===1&&<div className="wizard-form"><div><p className="eyebrow">STEP 1</p><h2>What should this dashboard help people decide?</h2></div><label>Dashboard name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Maintenance Operations Overview"/></label><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Business objective<textarea rows={4} value={form.businessObjective} onChange={e=>setForm({...form,businessObjective:e.target.value})} placeholder="Monitor maintenance backlog and fleet readiness…"/></label><div className="wizard-grid"><label>Target audience<input value={form.targetAudience} onChange={e=>setForm({...form,targetAudience:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Refresh expectation<select value={form.refreshExpectation} onChange={e=>setForm({...form,refreshExpectation:e.target.value})}><option>On demand</option><option>Every 15 minutes</option><option>Hourly</option><option>Daily</option></select></label><label>Default date range<select value={form.defaultDateRange} onChange={e=>setForm({...form,defaultDateRange:e.target.value})}><option>Last 7 days</option><option>Last 30 days</option><option>Current month</option><option>Current quarter</option><option>Current year</option></select></label></div><label>Business questions<div className="question-entry"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addQuestion();}}} placeholder="Which work orders are overdue?"/><button type="button" onClick={addQuestion}>Add</button></div></label><div className="question-chips">{form.businessQuestions.map(item=><button type="button" key={item} onClick={()=>setForm({...form,businessQuestions:form.businessQuestions.filter(value=>value!==item)})}>{item}<span>×</span></button>)}</div></div>}
      {step===2&&<div><p className="eyebrow">STEP 2</p><h2>Select published Business Context</h2><p className="wizard-hint">Choose a governed context, then let AI build and verify the first usable dashboard draft.</p><div className="context-choice">{contexts.map(item=><button type="button" className={form.businessContextModelId===item.id?"selected":""} key={item.id} onClick={()=>setForm({...form,businessContextModelId:item.id,businessContextVersionId:item.publishedVersion.id})}><span>Published v{item.publishedVersion.versionNumber}</span><strong>{item.name}</strong><p>{item.description||"Governed business definitions"}</p><small>{item.dataSource?.name} · {item.objectCount} objects · {item.kpiCount} approved KPIs</small></button>)}{!contexts.length&&<div className="workspace-empty"><strong>No accessible published context</strong><p>Ask a Business Context Manager to publish a model and grant Use for Dashboard access.</p></div>}</div>{form.businessContextVersionId&&<section className={`dashboard-ai-generate ${submitting?"is-running":""}`}><span aria-hidden="true">✦</span><div><strong>Generate a verified dashboard draft</strong><p>AI selects governed KPIs and filters, creates the layout and blocks, runs read-only previews, then opens Preview only after verification passes.</p></div><button className="primary-button" disabled={submitting||!purposeReady} onClick={()=>void submit("/api/dashboards/generate")}>{submitting&&<span className="button-spinner"/>}{submitting?"Generating and verifying…":"Generate with AI"}</button>{submitting&&generationProgress&&<AiGenerationProgress progress={generationProgress} elapsed={generationElapsed}/>}</section>}</div>}
      {step===3&&<div><p className="eyebrow">STEP 3</p><h2>Choose a responsive layout</h2><div className="layout-choice">{templates.map(item=><button type="button" className={form.layoutTemplateId===item.id?"selected":""} key={item.id} onClick={()=>setForm({...form,layoutTemplateId:item.id})}><span className="layout-mini"><i/><i/><i/><i/></span><strong>{item.name}</strong><p>{item.description}</p></button>)}</div></div>}
      {step===4&&<div className="wizard-review"><p className="eyebrow">STEP 4</p><h2>Review your dashboard foundation</h2><dl><div><dt>Dashboard</dt><dd>{form.name}</dd></div><div><dt>Objective</dt><dd>{form.businessObjective}</dd></div><div><dt>Audience</dt><dd>{form.targetAudience}</dd></div><div><dt>Business Context</dt><dd>{selectedContext?.name} · v{selectedContext?.publishedVersion.versionNumber}</dd></div><div><dt>Layout</dt><dd>{templates.find(item=>item.id===form.layoutTemplateId)?.name}</dd></div><div><dt>Questions</dt><dd>{form.businessQuestions.join(" · ")||form.businessObjective}</dd></div></dl><p className="governance-note">✓ Published context only · ✓ KPI versions locked · ✓ Read-only Oracle preview · ✓ Human approval required</p></div>}
      {error&&<p className="form-error" role="alert">{error}</p>}
      <footer className="wizard-actions"><button className="secondary-button" disabled={step===1||submitting} onClick={()=>setStep(step-1)}>← Back</button>{step<4?<button className="primary-button" disabled={(step===1&&!purposeReady)||(step===2&&!form.businessContextVersionId)||(step===3&&!form.layoutTemplateId)||submitting} onClick={()=>setStep(step+1)}>Continue →</button>:<button className="primary-button" disabled={submitting} onClick={()=>void submit("/api/dashboards")}>{submitting&&<span className="button-spinner"/>}{submitting?"Creating project…":"Create dashboard workspace"}</button>}</footer>
    </section>}
  </main>;
}
