"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { readAiProgressResponse, type AiProgress } from "@/lib/ai/progress-client";
import AiGenerationProgress from "@/components/shared/ai-generation-progress";

type Template={id:string;code:string;name:string;description:string;definitionJson:string};
type Context={id:string;name:string;description:string|null;publishedVersion:{id:string;versionNumber:number};dataSource?:{name:string};objectCount:number;kpiCount:number};

export default function DashboardCreateWizard(){
  const router=useRouter(); const [step,setStep]=useState(1); const [mode,setMode]=useState<"AI"|"MANUAL">("AI"); const [templates,setTemplates]=useState<Template[]>([]); const [contexts,setContexts]=useState<Context[]>([]); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState(""); const [question,setQuestion]=useState(""); const [generationProgress,setGenerationProgress]=useState<AiProgress|null>(null); const [generationElapsed,setGenerationElapsed]=useState(0);
  const [form,setForm]=useState({name:"",description:"",category:"Operations",businessObjective:"",targetAudience:"Operations managers",businessQuestions:[] as string[],refreshExpectation:"On demand",defaultDateRange:"Last 30 days",tags:[] as string[],businessContextModelId:"",businessContextVersionId:"",layoutTemplateId:""});
  const generationActive=submitting&&generationProgress!==null;
  useEffect(()=>{void fetch("/api/dashboards/options").then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setTemplates(body.templates??[]);setContexts(body.contexts??[]);}).catch((reason)=>setError(reason.message)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(!generationActive)return;const started=Date.now();const timer=window.setInterval(()=>setGenerationElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>window.clearInterval(timer);},[generationActive]);
  function addQuestion(){const value=question.trim();if(value&&!form.businessQuestions.includes(value))setForm({...form,businessQuestions:[...form.businessQuestions,value]});setQuestion("");}
  async function submit(path:string){const layoutTemplateId=form.layoutTemplateId||templates[0]?.id;const businessQuestions=form.businessQuestions.length?form.businessQuestions:[form.businessObjective];if(!layoutTemplateId)return setError("No active dashboard layout is available");const generated=path.endsWith("generate");setSubmitting(true);setError("");if(generated){setGenerationElapsed(0);setGenerationProgress({stage:"CONNECTING",label:"Starting dashboard generation",detail:"Opening a live progress connection to the structured dashboard pipeline.",percent:2});}else setGenerationProgress(null);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json",...(generated?{Accept:"text/event-stream"}:{})},body:JSON.stringify({...form,layoutTemplateId,businessQuestions})});const body=generated?await readAiProgressResponse<{previewPath?:string;dashboardId:string}>(response,setGenerationProgress):await response.json();if(!generated&&!response.ok)throw new Error(body.error||"Unable to create dashboard");router.push(generated?(body.previewPath||`/workspace/dashboards/${body.dashboardId}/edit?step=preview`):`/dashboards/${body.dashboardId}`);router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create dashboard");}finally{setSubmitting(false);}}
  const selectedContext=contexts.find((item)=>item.id===form.businessContextModelId);
  const purposeReady=Boolean(form.name.trim()&&form.businessObjective.trim());
  const labels=["Business Goal","Business Questions","Business Context","KPI Design","Data Mapping","Dashboard Structure","Visualization Design","Dashboard Layout","SQL & Preview","Validation","Publish"];
  const readyForNext=step===1?purposeReady:step===2?form.businessQuestions.length>0:step===3?Boolean(form.businessContextVersionId):step===8?Boolean(form.layoutTemplateId):true;
  return <main className="workspace-page dashboard-wizard-page">
    <header><p className="eyebrow">{mode==="AI"?"AI GUIDED DASHBOARD WIZARD":"BLANK DASHBOARD — MANUAL BUILDER"}</p><h1>Create dashboard project</h1><p>AI suggests from published Business Context; you retain control of every KPI, block, filter, layout, and SQL preview.</p></header>
    <div className="dashboard-mode-choice"><button type="button" className={mode==="AI"?"selected":""} onClick={()=>setMode("AI")}>✦ AI Guided Wizard<small>Suggestions are always editable</small></button><button type="button" className={mode==="MANUAL"?"selected":""} onClick={()=>setMode("MANUAL")}>＋ Blank Dashboard<small>Start with the manual builder</small></button></div>
    <nav className="wizard-steps wizard-steps-phase6" aria-label="Dashboard setup steps">{labels.map((label,index)=><button key={label} className={step===index+1?"active":step>index+1?"done":""} onClick={()=>step>index+1&&setStep(index+1)}><span>{step>index+1?"✓":index+1}</span>{label}</button>)}</nav>
    {loading?<div className="insight-loading"><span className="insight-spinner"/><span>Loading published business context…</span></div>:<section className="wizard-card">
      {step===1&&<div className="wizard-form"><div><p className="eyebrow">STEP 1</p><h2>What should this dashboard help people decide?</h2></div><label>Dashboard name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Maintenance Operations Overview"/></label><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Business objective<textarea rows={4} value={form.businessObjective} onChange={e=>setForm({...form,businessObjective:e.target.value})} placeholder="Monitor maintenance backlog and fleet readiness…"/></label><div className="wizard-grid"><label>Target audience<input value={form.targetAudience} onChange={e=>setForm({...form,targetAudience:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Refresh expectation<select value={form.refreshExpectation} onChange={e=>setForm({...form,refreshExpectation:e.target.value})}><option>On demand</option><option>Every 15 minutes</option><option>Hourly</option><option>Daily</option></select></label><label>Default date range<select value={form.defaultDateRange} onChange={e=>setForm({...form,defaultDateRange:e.target.value})}><option>Last 7 days</option><option>Last 30 days</option><option>Current month</option><option>Current quarter</option><option>Current year</option></select></label></div><label>Business questions<div className="question-entry"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addQuestion();}}} placeholder="Which work orders are overdue?"/><button type="button" onClick={addQuestion}>Add</button></div></label><div className="question-chips">{form.businessQuestions.map(item=><button type="button" key={item} onClick={()=>setForm({...form,businessQuestions:form.businessQuestions.filter(value=>value!==item)})}>{item}<span>×</span></button>)}</div></div>}
      {step===2&&<div className="wizard-form"><p className="eyebrow">STEP 2 — BUSINESS QUESTIONS</p><h2>Questions the dashboard must answer</h2><p className="wizard-hint">Add, edit, remove, and reorder questions. AI uses them as suggestions only.</p><label>Business questions<div className="question-entry"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addQuestion();}}} placeholder="Which work orders are overdue?"/><button type="button" onClick={addQuestion}>Add</button></div></label><div className="question-chips">{form.businessQuestions.map((item,index)=><span key={`${item}-${index}`}><input aria-label={`Question ${index+1}`} value={item} onChange={e=>setForm({...form,businessQuestions:form.businessQuestions.map((value,i)=>i===index?e.target.value:value)})}/><button type="button" disabled={!index} onClick={()=>setForm({...form,businessQuestions:form.businessQuestions.map((value,i)=>i===index?form.businessQuestions[index-1]:i===index-1?item:value)})}>↑</button><button type="button" disabled={index===form.businessQuestions.length-1} onClick={()=>setForm({...form,businessQuestions:form.businessQuestions.map((value,i)=>i===index?form.businessQuestions[index+1]:i===index+1?item:value)})}>↓</button><button type="button" onClick={()=>setForm({...form,businessQuestions:form.businessQuestions.filter((_,i)=>i!==index)})}>×</button></span>)}</div></div>}
      {step===3&&<div><p className="eyebrow">STEP 3 — BUSINESS CONTEXT</p><h2>Select published Business Context</h2><p className="wizard-hint">Review available Business Entities, Business Fields, Business Relationships, data quality, and data availability before generating recommendations.</p><div className="context-choice">{contexts.map(item=><button type="button" className={form.businessContextModelId===item.id?"selected":""} key={item.id} onClick={()=>setForm({...form,businessContextModelId:item.id,businessContextVersionId:item.publishedVersion.id})}><span>Published v{item.publishedVersion.versionNumber}</span><strong>{item.name}</strong><p>{item.description||"Governed business definitions"}</p><small>{item.dataSource?.name} · {item.objectCount} business entities · {item.kpiCount} approved KPIs</small></button>)}{!contexts.length&&<div className="workspace-empty"><strong>No accessible published context</strong><p>Ask a Business Context Manager to publish a model and grant Use for Dashboard access.</p></div>}</div></div>}
      {[4,5,6,7].includes(step)&&<div className="wizard-review"><p className="eyebrow">STEP {step} — {labels[step-1].toUpperCase()}</p><h2>{labels[step-1]}</h2><p>{mode==="AI"?"The wizard will recommend only KPIs, mappings, sections, and visualization types supported by the selected Business Context and actual available data. You may accept, edit, remove, or replace every suggestion.":"Manual mode starts empty. Use the builder to create and configure KPIs, datasets, visualizations, filters, and layout yourself."}</p><dl><div><dt>Business Context</dt><dd>{selectedContext?.name||"Select a published Business Context"}</dd></div><div><dt>Available KPIs</dt><dd>{selectedContext?.kpiCount??0} approved definitions</dd></div><div><dt>Data availability</dt><dd>{selectedContext?.objectCount??0} business entities from {selectedContext?.dataSource?.name||"the selected source"}</dd></div><div><dt>Your control</dt><dd>Every recommendation remains editable and needs explicit approval.</dd></div></dl></div>}
      {step===8&&<div><p className="eyebrow">STEP 8 — DASHBOARD LAYOUT</p><h2>Choose an initial responsive layout</h2><p className="wizard-hint">The manual editor uses a 12-column grid. Layout changes never regenerate SQL.</p><div className="layout-choice">{templates.map(item=><button type="button" className={form.layoutTemplateId===item.id?"selected":""} key={item.id} onClick={()=>setForm({...form,layoutTemplateId:item.id})}><span className="layout-mini"><i/><i/><i/><i/></span><strong>{item.name}</strong><p>{item.description}</p></button>)}</div></div>}
      {[9,10,11].includes(step)&&<div className="wizard-review"><p className="eyebrow">STEP {step} — {labels[step-1].toUpperCase()}</p><h2>{labels[step-1]}</h2><p>{step===9?"SQL is generated, validated, and previewed per dashboard block. After creation, regenerate or inspect a single block without rebuilding the dashboard.":step===10?"Validation checks formulas, SQL, mappings, joins, missing fields, data quality, visualization fit, and dashboard completeness.":"Publish only after review. Smart Filters, AI Copilot, export, and drill-down settings remain available in the Published Portal."}</p><p className="governance-note">✓ Actual available data only · ✓ Per-block query safety · ✓ Human approval required</p></div>}
      {error&&<p className="form-error" role="alert">{error}</p>}
      <footer className="wizard-actions"><button className="secondary-button" disabled={step===1||submitting} onClick={()=>setStep(step-1)}>← Back</button>{step<labels.length?<button className="primary-button" disabled={!readyForNext||submitting} onClick={()=>setStep(step+1)}>Continue →</button>:<button className="primary-button" disabled={submitting} onClick={()=>void submit(mode==="AI"?"/api/dashboards/generate":"/api/dashboards")}>{submitting&&<span className="button-spinner"/>}{submitting?(mode==="AI"?"Generating and verifying…":"Creating project…"):(mode==="AI"?"Generate dashboard with AI":"Create blank dashboard")}</button>}{submitting&&generationProgress&&<AiGenerationProgress progress={generationProgress} elapsed={generationElapsed}/>}</footer>
    </section>}
  </main>;
}
