"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useState} from "react";

type Dashboard={id:string;name:string;slug:string|null;thumbnailUrl:string|null;status:string;visibility:"PRIVATE"|"ROLE"|"WORKSPACE";exportAllowed:boolean;aiCopilotAllowed:boolean;underlyingDataAllowed:boolean;drillDownAllowed:boolean;isFeatured:boolean};
const roles=["VIEWER","DASHBOARD_CREATOR","DATA_SOURCE_CREATOR","ADMIN"] as const;
const capabilities=[
  ["aiCopilotAllowed","AI Copilot","Ask questions and generate executive summaries","✦"],
  ["exportAllowed","Export","Download permitted dashboard results","⇩"],
  ["underlyingDataAllowed","Underlying data","Inspect the governed rows behind a visual","▤"],
  ["drillDownAllowed","Drill down","Navigate from summaries into supporting detail","↳"],
  ["isFeatured","Featured","Highlight this dashboard in the Published Portal","★"],
] as const;

export default function PublishSettings({dashboard,canPublish}:{dashboard:Dashboard;canPublish:boolean}){
  const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState({slug:dashboard.slug||`dashboard-${dashboard.id}`,thumbnailUrl:dashboard.thumbnailUrl||"",visibility:dashboard.visibility,allowedRoles:["VIEWER","DASHBOARD_CREATOR"],exportAllowed:dashboard.exportAllowed,aiCopilotAllowed:dashboard.aiCopilotAllowed,underlyingDataAllowed:dashboard.underlyingDataAllowed,drillDownAllowed:dashboard.drillDownAllowed,isFeatured:dashboard.isFeatured});
  const enabledCapabilities=capabilities.filter(([key])=>form[key]).length;
  async function submit(action:"PUBLISH"|"UNPUBLISH"){setBusy(true);setError("");const response=await fetch(`/api/dashboards/${dashboard.id}/workflow`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action==="PUBLISH"?{action,...form,thumbnailUrl:form.thumbnailUrl||null}:{action})});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.error||"Unable to update publication");setOpen(false);router.refresh();}
  if(!canPublish&&dashboard.status!=="PUBLISHED")return null;
  return <section className="publish-settings-bar" aria-labelledby="published-portal-heading">
    <div className="publish-settings-summary">
      <span className="publish-settings-icon" aria-hidden="true">↗</span>
      <div className="publish-settings-copy"><p className="eyebrow">PUBLISHED PORTAL</p><h2 id="published-portal-heading">Viewer access and capabilities</h2><small>{dashboard.status==="PUBLISHED"?`Live at /dashboards/${dashboard.slug}`:"Configure the governed viewer experience before publishing."}</small></div>
      <div className="publish-settings-state"><span className={`publish-state ${dashboard.status.toLowerCase()}`}>{dashboard.status.replaceAll("_"," ")}</span><span>{dashboard.visibility.toLowerCase().replaceAll("_"," ")}</span><span>{enabledCapabilities} capabilities</span></div>
    </div>
    <div className="publish-settings-actions">{dashboard.status==="PUBLISHED"&&dashboard.slug&&<Link className="secondary-button" href={`/dashboards/${dashboard.slug}`}>Open portal <span aria-hidden="true">↗</span></Link>}<button className="primary-button" type="button" onClick={()=>setOpen(true)}>{dashboard.status==="PUBLISHED"?"View publication":"Configure publishing"}</button></div>
    {open&&<div className="publish-modal-backdrop" role="presentation" onMouseDown={()=>!busy&&setOpen(false)}><section className="publish-modal" role="dialog" aria-modal="true" aria-labelledby="publish-dialog-title" onMouseDown={event=>event.stopPropagation()}>
      <header><div className="publish-modal-heading"><span aria-hidden="true">↗</span><div><p className="eyebrow">PUBLISHED PORTAL</p><h2 id="publish-dialog-title">Viewer configuration</h2><small>Control where this dashboard appears and what viewers can do.</small></div></div><button className="publish-modal-close" type="button" onClick={()=>setOpen(false)} aria-label="Close publication settings">×</button></header>
      <div className="publish-modal-body">
        <section className="publish-config-section"><div className="publish-config-heading"><span>1</span><div><h3>Portal identity</h3><p>Set the viewer URL and optional preview image.</p></div></div><div className="publish-field-grid"><label>Public slug<div className="publish-slug-input"><span>/dashboards/</span><input value={form.slug} disabled={busy||dashboard.status==="PUBLISHED"} onChange={event=>setForm({...form,slug:event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")})}/></div></label><label>Thumbnail URL <small>Optional</small><input value={form.thumbnailUrl} disabled={busy||dashboard.status==="PUBLISHED"} onChange={event=>setForm({...form,thumbnailUrl:event.target.value})} placeholder="https://…"/></label></div></section>
        <section className="publish-config-section"><div className="publish-config-heading"><span>2</span><div><h3>Viewer access</h3><p>Choose who can discover and open the published dashboard.</p></div></div><label className="publish-audience-field">Audience<select value={form.visibility} disabled={busy||dashboard.status==="PUBLISHED"} onChange={event=>setForm({...form,visibility:event.target.value as typeof form.visibility})}><option value="WORKSPACE">Entire workspace</option><option value="ROLE">Selected roles</option><option value="PRIVATE">Specific users only</option></select></label>{form.visibility==="ROLE"?<fieldset className="publish-option-grid"><legend>Selected roles</legend>{roles.map(role=><label className="publish-option" key={role}><input type="checkbox" disabled={busy||dashboard.status==="PUBLISHED"} checked={form.allowedRoles.includes(role)} onChange={event=>setForm({...form,allowedRoles:event.target.checked?[...form.allowedRoles,role]:form.allowedRoles.filter(item=>item!==role)})}/><span className="publish-option-check" aria-hidden="true">✓</span><span><strong>{role.replaceAll("_"," ")}</strong><small>Allow this workspace role to view the dashboard</small></span></label>)}</fieldset>:<div className="publish-access-note"><strong>{form.visibility==="WORKSPACE"?"Available to the entire workspace":"Restricted viewer access"}</strong><p>{form.visibility==="WORKSPACE"?"All signed-in workspace users can discover and open this dashboard.":"Only users with explicit dashboard access can open this publication."}</p></div>}</section>
        <section className="publish-config-section publish-capability-section"><div className="publish-config-heading"><span>3</span><div><h3>Viewer capabilities</h3><p>Enable only the actions required by this dashboard’s audience.</p></div><b>{enabledCapabilities} enabled</b></div><fieldset className="publish-option-grid capability-grid"><legend className="sr-only">Viewer capabilities</legend>{capabilities.map(([key,label,description,icon])=><label className="publish-option capability-option" key={key}><input type="checkbox" disabled={busy||dashboard.status==="PUBLISHED"} checked={form[key]} onChange={event=>setForm({...form,[key]:event.target.checked})}/><span className="publish-capability-icon" aria-hidden="true">{icon}</span><span><strong>{label}</strong><small>{description}</small></span><span className="publish-option-check" aria-hidden="true">✓</span></label>)}</fieldset></section>
        <div className="publish-governance"><span aria-hidden="true">✓</span><div><strong>Governed viewer boundary</strong><p>Published viewers never receive Oracle credentials, generated SQL, physical schema details, or builder controls.</p></div></div>{dashboard.status==="PUBLISHED"&&<p className="publish-locked-note">Publication settings are locked while live. Unpublish before changing viewer access or capabilities.</p>}{error&&<p className="form-error" role="alert">{error}</p>}
      </div>
      <footer>{dashboard.status==="PUBLISHED"&&<button className="secondary-button danger" disabled={busy} onClick={()=>void submit("UNPUBLISH")}>{busy?"Unpublishing…":"Unpublish"}</button>}<span/><button className="secondary-button" disabled={busy} onClick={()=>setOpen(false)}>Close</button>{dashboard.status!=="PUBLISHED"&&<button className="primary-button" disabled={busy||!form.slug} onClick={()=>void submit("PUBLISH")}>{busy?"Publishing…":"Publish dashboard"}</button>}</footer>
    </section></div>}
  </section>;
}
