import { randomUUID } from "node:crypto";
import { and, asc, desc, eq, isNull } from "drizzle-orm";
import { db } from "@/lib/db";
import { aiConversations, aiMessages, aiUsageLogs, dashboardViewEvents } from "@/lib/db/schema";
import type { AuthenticatedUser } from "@/lib/auth/session";
import { HttpError } from "@/lib/http";
import { getPublishedDashboard, getPublishedDashboardRecord } from "./service";
import { isMutatingAiRequest, copilotRequestSchema } from "./validation";
import type { z } from "zod";

type Input=z.infer<typeof copilotRequestSchema>;
function config(){const apiKey=process.env.AI_API_KEY;const baseUrl=process.env.AI_BASE_URL?.replace(/\/$/,"");const model=process.env.AI_MODEL;if(!apiKey||!baseUrl||!model)throw new HttpError(503,"AI Copilot is not configured","AI_NOT_CONFIGURED");return{apiKey,baseUrl,model,provider:(process.env.AI_PROVIDER||"openai").toLowerCase()}}
function responseText(body:{output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>;choices?:Array<{message?:{content?:string}}>}){return body.output_text||body.output?.flatMap(item=>item.content||[]).map(item=>item.text||"").join("\n")||body.choices?.[0]?.message?.content||""}
function structured(content:string){if (/^## Summary/m.test(content)) return content;return `## Summary\n${content}\n\n## Key Findings\n- Review the dashboard evidence above.\n\n## Evidence\n- Published dashboard context and governed KPI results.\n\n## Possible Explanation\n- Treat explanations as hypotheses unless confirmed by an owner.\n\n## Recommended Follow-up\n- Validate the finding with the responsible business owner.`}
const refusal="## Summary\nI can explain published dashboard results, but I cannot edit data, change filters permanently, modify dashboards, or perform workflow actions.\n\n## Key Findings\n- This Copilot is read-only.\n\n## Evidence\n- No write or publishing tools are available to the AI.\n\n## Possible Explanation\n- Governance keeps executive analysis separate from creator actions.\n\n## Recommended Follow-up\n- Open the Creator Workspace or contact the dashboard owner for changes.";

export async function runDashboardCopilot(input:Input,user:AuthenticatedUser){
  const record=await getPublishedDashboardRecord(input.dashboardSlug,user);const viewer=await getPublishedDashboard(input.dashboardSlug,user);
  if(!viewer.capabilities.ai)throw new HttpError(403,"AI Copilot is disabled for this dashboard","AI_DISABLED");
  const cfg=config();const now=new Date();let conversationId=input.conversationId;const conversation=conversationId?(await db.select().from(aiConversations).where(and(eq(aiConversations.id,conversationId),eq(aiConversations.userId,user.id),eq(aiConversations.dashboardId,record.dashboard.id),isNull(aiConversations.deletedAt))).limit(1))[0]:undefined;
  if(conversationId&&!conversation)throw new HttpError(404,"Conversation not found","NOT_FOUND");
  if(!conversation){conversationId=randomUUID();await db.insert(aiConversations).values({id:conversationId,userId:user.id,dashboardId:record.dashboard.id,title:(input.question||"Executive summary").slice(0,190),filtersSnapshotJson:JSON.stringify(input.filters),createdAt:now,updatedAt:now});}
  const question=input.requestType==="EXECUTIVE_SUMMARY"?"Generate an executive summary of this dashboard, emphasizing material changes, exceptions, targets, and decisions.":input.question!;
  await db.insert(aiMessages).values({id:randomUUID(),conversationId:conversationId!,role:"USER",content:question,widgetId:input.widgetId,filtersSnapshotJson:JSON.stringify(input.filters),createdAt:now});
  const started=Date.now();
  if(isMutatingAiRequest(question)){await saveAssistant({conversationId:conversationId!,user,dashboardId:record.dashboard.id,requestType:input.requestType,content:refusal,model:cfg.model,started,status:"REFUSED"});return{conversationId,answer:refusal,refused:true};}
  const history=await db.select({role:aiMessages.role,content:aiMessages.content}).from(aiMessages).where(eq(aiMessages.conversationId,conversationId!)).orderBy(asc(aiMessages.createdAt)).limit(20);
  const context={dashboard:{name:viewer.dashboard.name,description:viewer.dashboard.description,category:viewer.dashboard.category,publishedAt:viewer.dashboard.publishedAt},activeFilters:input.filters,selectedWidgetId:input.widgetId||null,widgets:viewer.blocks.map(block=>({id:block.id,title:block.title,description:block.description,businessQuestion:block.businessQuestion,decisionSupported:block.decisionSupported,visualization:block.visualizationType,aggregatedPublishedPreview:block.preview})),guardrails:{readOnly:true,noWriteActions:true,noCredentials:true,noSql:true,noTechnicalSchema:true,explanationsAreHypotheses:true}};
  const system="You are IFS Insight Executive AI Copilot. Use only the authorized published dashboard context supplied. Never claim access to data outside it. Never edit, write, publish, approve, delete, or instruct a database action. Do not reveal SQL, physical schemas, credentials, internal IDs, or hidden configuration. Clearly distinguish facts from possible explanations. Answer concisely in Markdown with exactly these headings: Summary, Key Findings, Evidence, Possible Explanation, Recommended Follow-up. If evidence is insufficient, say so.";
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45_000);
  try{
    const useResponses=cfg.provider==="openai"||/api\.openai\.com/i.test(cfg.baseUrl);const url=`${cfg.baseUrl}/${useResponses?"responses":"chat/completions"}`;
    const payload=useResponses?{model:cfg.model,instructions:system,input:[...history.map(item=>({role:item.role==="USER"?"user":"assistant",content:item.content})),{role:"user",content:`Authorized context:\n${JSON.stringify(context)}\n\nRequest:\n${question}`}],reasoning:{effort:"low"},text:{verbosity:"medium"}}:{model:cfg.model,temperature:.2,messages:[{role:"system",content:system},...history.map(item=>({role:item.role==="USER"?"user":"assistant",content:item.content})),{role:"user",content:`Authorized context:\n${JSON.stringify(context)}\n\nRequest:\n${question}`}]};
    const response=await fetch(url,{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",authorization:`Bearer ${cfg.apiKey}`},body:JSON.stringify(payload)});const body=await response.json() as {output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>;choices?:Array<{message?:{content?:string}}> ;usage?:{input_tokens?:number;output_tokens?:number;prompt_tokens?:number;completion_tokens?:number};error?:{message?:string}};if(!response.ok)throw new Error(body.error?.message||"AI provider request failed");const answer=structured(responseText(body));await saveAssistant({conversationId:conversationId!,user,dashboardId:record.dashboard.id,requestType:input.requestType,content:answer,model:cfg.model,started,status:"SUCCESS",inputTokens:body.usage?.input_tokens??body.usage?.prompt_tokens,outputTokens:body.usage?.output_tokens??body.usage?.completion_tokens});return{conversationId,answer,refused:false};
  }catch(error){await saveAssistant({conversationId:conversationId!,user,dashboardId:record.dashboard.id,requestType:input.requestType,content:"AI analysis is temporarily unavailable.",model:cfg.model,started,status:"FAILED",errorCode:error instanceof Error&&error.name==="AbortError"?"TIMEOUT":"PROVIDER_ERROR"});throw new HttpError(502,error instanceof Error&&error.name==="AbortError"?"AI analysis timed out":"AI analysis is temporarily unavailable","AI_REQUEST_FAILED");}finally{clearTimeout(timer)}
}

async function saveAssistant(input:{conversationId:string;user:AuthenticatedUser;dashboardId:string;requestType:"CHAT"|"EXECUTIVE_SUMMARY";content:string;model:string;started:number;status:"SUCCESS"|"FAILED"|"REFUSED";inputTokens?:number;outputTokens?:number;errorCode?:string}){const createdAt=new Date();const latencyMs=Date.now()-input.started;await db.transaction(async tx=>{await tx.insert(aiMessages).values({id:randomUUID(),conversationId:input.conversationId,role:"ASSISTANT",content:input.content,model:input.model,inputTokens:input.inputTokens,outputTokens:input.outputTokens,latencyMs,errorCode:input.errorCode,createdAt});await tx.insert(aiUsageLogs).values({id:randomUUID(),userId:input.user.id,dashboardId:input.dashboardId,conversationId:input.conversationId,requestType:input.requestType,model:input.model,inputTokens:input.inputTokens||0,outputTokens:input.outputTokens||0,latencyMs,status:input.status,errorCode:input.errorCode,createdAt});await tx.update(aiConversations).set({updatedAt:createdAt}).where(eq(aiConversations.id,input.conversationId));await tx.insert(dashboardViewEvents).values({id:randomUUID(),userId:input.user.id,dashboardId:input.dashboardId,eventType:input.requestType==="EXECUTIVE_SUMMARY"?"EXECUTIVE_SUMMARY":"AI_CHAT",createdAt});});}

export async function listDashboardConversations(slug:string,user:AuthenticatedUser){const record=await getPublishedDashboardRecord(slug,user);const conversations=await db.select().from(aiConversations).where(and(eq(aiConversations.userId,user.id),eq(aiConversations.dashboardId,record.dashboard.id),isNull(aiConversations.deletedAt))).orderBy(desc(aiConversations.updatedAt)).limit(30);return conversations.map(item=>({id:item.id,title:item.title,updatedAt:item.updatedAt}));}
