import Link from "next/link";

export default function LandingPage() {
  return <main className="landing-page">
    <nav className="landing-nav" aria-label="Public navigation"><Link className="landing-brand" href="/"><span>✦</span> IFS <b>Insight</b></Link><div><a href="#capabilities">Capabilities</a><a href="#security">Security</a><Link className="landing-signin" href="/login">Sign in</Link></div></nav>
    <section className="landing-hero"><div className="landing-orb orb-one"/><div className="landing-orb orb-two"/><div className="landing-hero-copy"><p className="landing-kicker"><span/>ORACLE INTELLIGENCE, MADE CLEAR</p><h1>Turn IFS data into<br/><em>decisions that move.</em></h1><p>Connect trusted Oracle data, understand every relationship, and build decision-ready dashboards from one governed workspace.</p><div className="landing-actions"><Link className="landing-primary" href="/login">Explore your workspace<span>→</span></Link><a className="landing-secondary" href="#capabilities">See capabilities</a></div><div className="landing-trust"><span><b>Read-only</b> Oracle access</span><span><b>Encrypted</b> credentials</span><span><b>Role-based</b> governance</span></div></div>
      <div className="landing-preview" aria-label="IFS Insight product preview"><div className="preview-bar"><span/><span/><span/><small>IFS Insight / Executive overview</small></div><div className="preview-body"><aside><b>✦</b><i/><i/><i/><i/></aside><section><div className="preview-heading"><div><small>EXECUTIVE OVERVIEW</small><strong>Good morning, your data is ready.</strong></div><span>Live</span></div><div className="preview-metrics"><article><small>Connected sources</small><b>12</b><em>All healthy</em></article><article><small>Metadata objects</small><b>339K</b><em>Synced today</em></article><article><small>Active dashboards</small><b>28</b><em>Across 6 teams</em></article></div><div className="preview-chart"><div><small>Operational trend</small><strong>IFS Performance</strong></div><svg viewBox="0 0 520 155" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7c3aed" stopOpacity=".32"/><stop offset="1" stopColor="#7c3aed" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 135 C60 120 70 98 120 105 S190 135 230 82 S305 55 345 70 S420 25 520 30 L520 155 L0 155Z"/><path className="line" d="M0 135 C60 120 70 98 120 105 S190 135 230 82 S305 55 345 70 S420 25 520 30"/></svg></div></section></div></div>
    </section>
    <section id="capabilities" className="landing-capabilities"><p className="landing-kicker"><span/>ONE GOVERNED WORKSPACE</p><h2>From connection to clarity.</h2><div><article><span>01</span><h3>Connect with confidence</h3><p>Secure, read-only Oracle connections with encrypted credentials and complete health visibility.</p></article><article><span>02</span><h3>Understand your IFS model</h3><p>Explore schemas, tables, columns, keys, and relationships without digging through the data dictionary.</p></article><article><span>03</span><h3>Build what matters</h3><p>A governed foundation ready for Phase 3 dashboards, visual analysis, and AI-assisted insights.</p></article></div></section>
    <section id="security" className="landing-security"><div><p className="landing-kicker"><span/>BUILT FOR ENTERPRISE TRUST</p><h2>Your data stays governed.</h2></div><p>Read-only Oracle access, AES-256-GCM credential encryption, granular permissions, sensitive-field masking, and a complete audit trail are built into the platform—not added later.</p></section>
    <footer className="landing-footer"><Link className="landing-brand" href="/"><span>✦</span> IFS <b>Insight</b></Link><p>Trusted data. Clear decisions.</p><small>© 2026 IFS Insight</small></footer>
  </main>;
}
