"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

type Item={id:string;slug:string;name:string;description:string|null;category:string;thumbnailUrl:string|null;featured:boolean;viewCount:number;favorite:boolean;recentAt:string|null;publishedAt:string;capabilities:{export:boolean;ai:boolean}};
export default function DashboardPortal({initialJson}:{initialJson:string}){
  const initial=JSON.parse(initialJson) as Item[];const params=useSearchParams();const selectedView=params.get("view")||"all";const [items,setItems]=useState(initial);const [query,setQuery]=useState("");const [category,setCategory]=useState("All");const [sort,setSort]=useState("featured");
  const categories=["All",...new Set(items.map(item=>item.category))];
  const visible=useMemo(()=>items.filter(item=>(selectedView!=="favorites"||item.favorite)&&(selectedView!=="recent"||item.recentAt)&&(category==="All"||item.category===category)&&(`${item.name} ${item.description||""}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="popular"?b.viewCount-a.viewCount:sort==="recent"?new Date(b.recentAt||b.publishedAt).getTime()-new Date(a.recentAt||a.publishedAt).getTime():Number(b.featured)-Number(a.featured)),[items,selectedView,category,query,sort]);
  async function favorite(item:Item){const next=!item.favorite;setItems(current=>current.map(value=>value.id===item.id?{...value,favorite:next}:value));const response=await fetch(`/api/published-dashboards/${item.slug}/favorite`,{method:next?"POST":"DELETE"});if(!response.ok)setItems(current=>current.map(value=>value.id===item.id?{...value,favorite:!next}:value));}
  return <main className="published-page"><section className="portal-hero"><div><p className="eyebrow">IFS INSIGHT PORTAL</p><h1>Decisions start with trusted data.</h1><p>Open published executive dashboards built from governed Business Context and approved KPI definitions.</p></div><div className="portal-hero-stat"><span>Available to you</span><strong>{items.length}</strong><small>published dashboards</small></div></section><section className="portal-toolbar" aria-label="Dashboard discovery"><label><span>Search dashboards</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by name or purpose…"/></label><label><span>Category</span><select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(value=><option key={value}>{value}</option>)}</select></label><label><span>Sort</span><select value={sort} onChange={event=>setSort(event.target.value)}><option value="featured">Featured</option><option value="recent">Recently viewed</option><option value="popular">Most viewed</option><option value="name">Name</option></select></label></section><div className="portal-section-head"><div><p className="eyebrow">{selectedView.toUpperCase()}</p><h2>{selectedView==="favorites"?"Your favorites":selectedView==="recent"?"Recently viewed":"Published dashboards"}</h2></div><span>{visible.length} results</span></div><section className="portal-grid">{visible.map(item=><article className="portal-card" key={item.id}><div className="portal-card-art" style={item.thumbnailUrl?{backgroundImage:`linear-gradient(135deg,rgba(48,16,84,.35),rgba(108,63,212,.08)),url(${item.thumbnailUrl})`}:undefined}><span>{item.category}</span><button aria-label={item.favorite?"Remove from favorites":"Add to favorites"} aria-pressed={item.favorite} onClick={()=>void favorite(item)}>{item.favorite?"★":"☆"}</button></div><div><h3>{item.name}</h3><p>{item.description||"Governed executive intelligence for confident decisions."}</p><div className="portal-card-meta"><span>{item.viewCount} views</span><span>Published {new Date(item.publishedAt).toLocaleDateString()}</span></div><Link className="primary-button" href={`/dashboards/${item.slug}`}>Open dashboard <span>→</span></Link></div></article>)}{!visible.length&&<div className="portal-empty"><span>⌁</span><h3>No dashboards found</h3><p>Try another search or category. Only dashboards you are permitted to view appear here.</p></div>}</section></main>;
}
