"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
const DashboardCopilot=dynamic(()=>import("./dashboard-copilot"),{ssr:false,loading:()=> <div className="copilot-loading"><span className="insight-spinner"/>Opening AI Copilot…</div>});
type Block={id:string;title:string;description:string|null;businessQuestion:string|null;decisionSupported:string|null;blockType:string;visualizationType:string;position:{x:number;y:number;w:number;h:number};preview:{rows?:Record<string,unknown>[]} | null};
type Filter={id:string;name:string;filterType:string;defaultValue:unknown;allowedValues:unknown[];required:boolean;runtimeEditable:boolean};
type Data={dashboard:{id:string;slug:string;name:string;description:string|null;category:string;publishedAt:string;lastDataRefreshAt:string|null;favorite:boolean};blocks:Block[];filters:Filter[];capabilities:{export:boolean;underlyingData:boolean;drillDown:boolean;ai:boolean;executiveSummary:boolean};suggestedQuestions:string[]};
type Result={rows:Record<string,unknown>[];rowCount:number;durationMs:number;executedAt:string};
export default function ExecutiveDashboardViewer({initialJson}:{initialJson:string}){
  const data=JSON.parse(initialJson) as Data;const [favorite,setFavorite]=useState(data.dashboard.favorite);const [copilot,setCopilot]=useState(false);const [filters,setFilters]=useState<Record<string,(string|number|boolean|null)[]>>(()=>Object.fromEntries(data.filters.map(item=>[item.id,Array.isArray(item.defaultValue)?item.defaultValue:item.defaultValue==null?[]:[item.defaultValue as string]])));const [applied,setApplied]=useState(filters);const [results,setResults]=useState<Record<string,{state:"loading"|"ready"|"error";data?:Result;error?:string}>>({});
  const filterPayload=useMemo(()=>Object.entries(applied).map(([filterId,values])=>({filterId,values})),[applied]);
  async function load(block:Block){if(block.blockType==="TEXT_INSIGHT")return;setResults(current=>({...current,[block.id]:{state:"loading"}}));try{const response=await fetch(`/api/published-dashboards/${data.dashboard.slug}/widgets/${block.id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filters:filterPayload})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Widget could not be loaded");setResults(current=>({...current,[block.id]:{state:"ready",data:body}}));}catch(error){setResults(current=>({...current,[block.id]:{state:"error",error:error instanceof Error?error.message:"Widget could not be loaded"}}));}}
  useEffect(()=>{void fetch(`/api/published-dashboards/${data.dashboard.slug}/view`,{method:"POST"});data.blocks.forEach(block=>void load(block));},[data.dashboard.slug,JSON.stringify(filterPayload)]);// eslint-disable-line react-hooks/exhaustive-deps
  async function toggleFavorite(){const next=!favorite;setFavorite(next);const response=await fetch(`/api/published-dashboards/${data.dashboard.slug}/favorite`,{method:next?"POST":"DELETE"});if(!response.ok)setFavorite(!next);}
  return <main className="executive-viewer"><header className="viewer-head"><div><Link href="/dashboards">← Published dashboards</Link><p className="eyebrow">{data.dashboard.category} · PUBLISHED</p><h1>{data.dashboard.name}</h1><p>{data.dashboard.description}</p><small>Published {new Date(data.dashboard.publishedAt).toLocaleDateString()} · Data refreshed {data.dashboard.lastDataRefreshAt?new Date(data.dashboard.lastDataRefreshAt).toLocaleString():"on demand"}</small></div><div><button className="secondary-button viewer-favorite" onClick={()=>void toggleFavorite()}>{favorite?"★ Favorited":"☆ Favorite"}</button>{data.capabilities.ai&&<button className="primary-button" onClick={()=>setCopilot(true)}>✦ Ask IFS Insight</button>}</div></header>{data.filters.length>0&&<section className="viewer-filters"><div className="viewer-filter-fields">{data.filters.map(filter=><label key={filter.id}><span>{filter.name}{filter.required&&" *"}</span>{filter.allowedValues.length?<select disabled={!filter.runtimeEditable} value={String(filters[filter.id]?.[0]??"")} onChange={event=>setFilters(current=>({...current,[filter.id]:event.target.value?[event.target.value]:[]}))}><option value="">All</option>{filter.allowedValues.map(value=><option value={String(value)} key={String(value)}>{String(value)}</option>)}</select>:<input disabled={!filter.runtimeEditable} type={filter.filterType.includes("DATE")?"date":"text"} value={String(filters[filter.id]?.[0]??"")} onChange={event=>setFilters(current=>({...current,[filter.id]:event.target.value?[event.target.value]:[]}))}/>}</label>)}</div><div><button className="secondary-button" onClick={()=>{const cleared=Object.fromEntries(data.filters.map(item=>[item.id,[]]));setFilters(cleared);setApplied(cleared);}}>Clear</button><button className="primary-button" onClick={()=>setApplied(filters)}>Apply filters</button></div></section>}<section className="viewer-grid">{data.blocks.map(block=><ViewerWidget key={block.id} block={block} result={results[block.id]} onRetry={()=>void load(block)}/>)}</section>{copilot&&<DashboardCopilot dashboardSlug={data.dashboard.slug} dashboardName={data.dashboard.name} filters={filterPayload} suggestedQuestions={data.suggestedQuestions} canSummary={data.capabilities.executiveSummary} onClose={()=>setCopilot(false)}/>}</main>;
}
function ViewerWidget({block,result,onRetry}:{block:Block;result?:{state:"loading"|"ready"|"error";data?:Result;error?:string};onRetry:()=>void}){const rows=result?.data?.rows??block.preview?.rows??[];const values=rows.slice(0,8).map(row=>({label:String(row.DIMENSION_VALUE??row.dimension_value??"Current"),value:Number(row.KPI_VALUE??row.kpi_value??Object.values(row)[0]??0)}));const max=Math.max(1,...values.map(item=>Math.abs(item.value)));return <article className={`viewer-widget span-${Math.min(12,Math.max(4,block.position.w||6))}`}><header><div><p>{block.blockType.replaceAll("_"," ")}</p><h2>{block.title}</h2></div>{result?.state==="ready"&&<span className="live-dot">LIVE</span>}</header>{block.description&&<p className="widget-description">{block.description}</p>}{result?.state==="loading"&&<div className="widget-state"><span className="insight-spinner"/><strong>Loading trusted data…</strong></div>}{result?.state==="error"&&<div className="widget-state error"><strong>Unable to load this insight</strong><p>{result.error}</p><button onClick={onRetry}>Retry</button></div>}{block.blockType==="TEXT_INSIGHT"&&<div className="text-insight"><span>INSIGHT</span><p>{block.decisionSupported||block.businessQuestion||block.description}</p></div>}{result?.state!=="loading"&&result?.state!=="error"&&block.blockType!=="TEXT_INSIGHT"&&(block.visualizationType==="NUMBER"?<div className="kpi-number"><strong>{values[0]?.value.toLocaleString()??"—"}</strong><span>{values[0]?.label}</span></div>:block.visualizationType.includes("TABLE")||block.blockType.includes("TABLE")?<div className="viewer-table-wrap"><table><thead><tr>{Object.keys(rows[0]||{}).map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.slice(0,10).map((row,index)=><tr key={index}>{Object.values(row).map((value,i)=><td key={i}>{String(value??"—")}</td>)}</tr>)}</tbody></table></div>:<div className="mini-bars">{values.map(item=><div key={item.label}><span>{item.label}</span><i><b style={{width:`${Math.max(3,Math.abs(item.value)/max*100)}%`}}/></i><strong>{item.value.toLocaleString()}</strong></div>)}</div>)}{result?.data&&<footer>Updated {new Date(result.data.executedAt).toLocaleTimeString()} · {result.data.durationMs} ms</footer>}</article>}
