"use client";
import { useEffect, useMemo, useState } from "react";

type Value = string | number | boolean | null;
type FilterConfiguration = { controlType:string;selectionMode:"SINGLE"|"MULTIPLE";placeholder:string;allowSelectAll:boolean;allowClear:boolean;searchable:boolean;searchMode:"CLIENT"|"SERVER";minimumSearchCharacters:number;pageSize:number;maximumSelectedItems:number;relativeDatePresets:string[];dependsOn:string[];applyMode:"MANUAL"|"AUTO";position:number;reason:string };
export type PublishedSmartFilter={id:string;name:string;filterType:string;dataType:string;semanticRole:string;fieldName:string;defaultValue:unknown;allowedValues:unknown[];affectedBlockIds:string[];required:boolean;runtimeEditable:boolean;urlStateAllowed:boolean;configuration:FilterConfiguration};
type FilterState=Record<string,Value[]>;
type SavedView={name:string;values:FilterState;isDefault?:boolean};

const valuesEqual=(a:FilterState,b:FilterState)=>JSON.stringify(a)===JSON.stringify(b);
export function defaultFilterState(filters:PublishedSmartFilter[]):FilterState{return Object.fromEntries(filters.map(item=>[item.id,Array.isArray(item.defaultValue)?item.defaultValue as Value[]:item.defaultValue==null?[]:[item.defaultValue as Value]]));}
export function initialFilterState(filters:PublishedSmartFilter[]):FilterState{const state=defaultFilterState(filters);if(typeof window==="undefined")return state;const url=new URL(window.location.href);filters.forEach(filter=>{if(!filter.urlStateAllowed)return;const encoded=url.searchParams.get(`f_${filter.id}`);if(encoded)try{const parsed=JSON.parse(encoded) as Value[];if(Array.isArray(parsed))state[filter.id]=parsed;}catch{/* Ignore malformed bookmark state. */}});return state;}
function activeCount(values:FilterState){return Object.values(values).filter(item=>item.length).length;}
function presetRange(preset:string):Value[]{const now=new Date();const start=new Date(now);const end=new Date(now);const day=(date:Date)=>date.toISOString().slice(0,10);if(preset==="YESTERDAY"){start.setDate(now.getDate()-1);end.setDate(now.getDate()-1);}if(preset==="LAST_7_DAYS")start.setDate(now.getDate()-6);if(preset==="LAST_30_DAYS")start.setDate(now.getDate()-29);if(preset==="THIS_WEEK")start.setDate(now.getDate()-((now.getDay()+6)%7));if(preset==="LAST_WEEK"){start.setDate(now.getDate()-((now.getDay()+6)%7)-7);end.setTime(start.getTime());end.setDate(start.getDate()+6);}if(preset==="THIS_MONTH")start.setDate(1);if(preset==="LAST_MONTH"){start.setMonth(now.getMonth()-1,1);end.setDate(0);}if(preset==="THIS_QUARTER")start.setMonth(Math.floor(now.getMonth()/3)*3,1);if(preset==="THIS_YEAR")start.setMonth(0,1);return[day(start),day(end)];}

export default function SmartDashboardFilters({dashboardSlug,filters,values,onApply}:{dashboardSlug:string;filters:PublishedSmartFilter[];values:FilterState;onApply:(next:FilterState)=>void}){
  const storageKey=`insightfs:filter-views:${dashboardSlug}`;const[draft,setDraft]=useState(values);const[moreOpen,setMoreOpen]=useState(false);const[error,setError]=useState("");const[savedViews,setSavedViews]=useState<SavedView[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(storageKey)??"[]") as SavedView[];}catch{return[];}});const[savedName,setSavedName]=useState("");
  const ordered=useMemo(()=>[...filters].sort((a,b)=>a.configuration.position-b.configuration.position),[filters]);const primary=ordered.slice(0,4);const additional=ordered.slice(4);
  useEffect(()=>{const timer=window.setTimeout(()=>{const url=new URL(window.location.href);const hasUrlState=filters.some(filter=>filter.urlStateAllowed&&url.searchParams.has(`f_${filter.id}`));const defaultView=savedViews.find(view=>view.isDefault);const initial=hasUrlState?initialFilterState(filters):defaultView?{...defaultFilterState(filters),...defaultView.values}:initialFilterState(filters);if(!valuesEqual(initial,values)){setDraft(initial);onApply(initial);}},0);return()=>window.clearTimeout(timer);},[]);// eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const pop=()=>{const url=new URL(window.location.href);const next=defaultFilterState(filters);filters.forEach(filter=>{if(!filter.urlStateAllowed)return;const encoded=url.searchParams.get(`f_${filter.id}`);if(encoded)try{const parsed=JSON.parse(encoded) as Value[];if(Array.isArray(parsed))next[filter.id]=parsed;}catch{/* Ignore malformed history state. */}});setDraft(next);onApply(next);};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop);},[filters,onApply]);
  function persistUrl(next:FilterState){const url=new URL(window.location.href);filters.forEach(filter=>{const key=`f_${filter.id}`;if(!filter.urlStateAllowed||!next[filter.id]?.length)url.searchParams.delete(key);else url.searchParams.set(key,JSON.stringify(next[filter.id]));});history.pushState({},"",url);}
  function validate(next:FilterState){for(const filter of filters){const current=next[filter.id]??[];if(filter.required&&!current.length)return`${filter.name} is required.`;if(filter.filterType==="DATE_RANGE"&&current.length===2&&String(current[0])>String(current[1]))return`${filter.name}: From date must not be later than To date.`;if(filter.filterType==="NUMERIC_RANGE"&&current.length===2&&Number(current[0])>Number(current[1]))return`${filter.name}: Minimum must not be greater than maximum.`;}return"";}
  function apply(next=draft){const message=validate(next);setError(message);if(message)return;persistUrl(next);onApply(next);setMoreOpen(false);}
  function change(filter:PublishedSmartFilter,nextValues:Value[]){let next={...draft,[filter.id]:nextValues};const resetChildren=(parentId:string,visited=new Set<string>())=>{if(visited.has(parentId))return;visited.add(parentId);filters.filter(item=>item.configuration.dependsOn.includes(parentId)).forEach(child=>{next={...next,[child.id]:[]};resetChildren(child.id,visited);});};resetChildren(filter.id);setDraft(next);if(filter.configuration.applyMode==="AUTO")apply(next);}
  function reset(){const next=defaultFilterState(filters);setDraft(next);apply(next);}function clear(){const next=Object.fromEntries(filters.map(item=>[item.id,[]]));setDraft(next);apply(next);}
  function removeChip(id:string){const next={...draft,[id]:[]};setDraft(next);apply(next);}
  function saveView(){const name=savedName.trim();if(!name)return;const safeValues=Object.fromEntries(filters.filter(item=>item.urlStateAllowed).map(item=>[item.id,draft[item.id]??[]]));const next=[...savedViews.filter(item=>item.name!==name),{name,values:safeValues}];setSavedViews(next);setSavedName("");localStorage.setItem(storageKey,JSON.stringify(next));}
  function deleteView(name:string){const next=savedViews.filter(item=>item.name!==name);setSavedViews(next);localStorage.setItem(storageKey,JSON.stringify(next));}
  function renameView(view:SavedView){const name=window.prompt("Rename saved view",view.name)?.trim();if(!name||name===view.name)return;const next=savedViews.filter(item=>item.name!==name).map(item=>item.name===view.name?{...item,name}:item);setSavedViews(next);localStorage.setItem(storageKey,JSON.stringify(next));}
  function setDefaultView(name:string){const next=savedViews.map(item=>({...item,isDefault:item.name===name?!item.isDefault:false}));setSavedViews(next);localStorage.setItem(storageKey,JSON.stringify(next));}
  const filterFields=(items:PublishedSmartFilter[])=><>{items.map(filter=><SmartFilterControl key={filter.id} dashboardSlug={dashboardSlug} filter={filter} values={draft[filter.id]??[]} allValues={draft} onChange={next=>change(filter,next)}/>)}</>;
  return <section className="smart-filter-shell" aria-label="Dashboard filters"><div className="smart-filter-mobile-head"><button className="secondary-button" onClick={()=>setMoreOpen(true)}>☰ Filters <span>{activeCount(values)}</span></button></div><div className="smart-filter-desktop"><div className="smart-filter-primary">{filterFields(primary)}</div><div className="smart-filter-actions">{additional.length>0&&<button className="secondary-button" onClick={()=>setMoreOpen(true)}>More filters <span>{additional.length}</span></button>}<button className="secondary-button" onClick={reset}>Reset</button><button className="secondary-button" onClick={clear}>Clear all</button><button className="primary-button" disabled={valuesEqual(draft,values)} onClick={()=>apply()}>Apply</button></div></div>{activeCount(values)>0&&<div className="active-filter-row"><strong>{activeCount(values)} active</strong>{filters.flatMap(filter=>(values[filter.id]??[]).length?[<button key={filter.id} onClick={()=>removeChip(filter.id)}>{filter.name}: {(values[filter.id]??[]).map(String).join(", ")} <span>×</span></button>]:[])}</div>}{error&&<p className="smart-filter-error" role="alert">{error}</p>}{moreOpen&&<><button className="smart-filter-backdrop" aria-label="Close filters" onClick={()=>setMoreOpen(false)}/><aside className="smart-filter-drawer" aria-label="More dashboard filters"><header><div><p className="eyebrow">SMART FILTERS</p><h2>Refine dashboard</h2></div><button aria-label="Close filters" onClick={()=>setMoreOpen(false)}>×</button></header><div className="smart-filter-drawer-fields">{filterFields(ordered)}</div><section className="saved-filter-views"><strong>Personal saved views</strong>{savedViews.map(view=><div key={view.name}><button onClick={()=>{setDraft({...defaultFilterState(filters),...view.values});}}>{view.isDefault?"★ ":""}{view.name}</button><button aria-label={`Set ${view.name} as default`} title="Set as default" onClick={()=>setDefaultView(view.name)}>★</button><button aria-label={`Rename ${view.name}`} title="Rename" onClick={()=>renameView(view)}>✎</button><button aria-label={`Delete ${view.name}`} title="Delete" onClick={()=>deleteView(view.name)}>×</button></div>)}<label><span>Save current view</span><div><input value={savedName} onChange={event=>setSavedName(event.target.value)} placeholder="e.g. This month"/><button disabled={!savedName.trim()} onClick={saveView}>Save</button></div></label></section><footer><button className="secondary-button" onClick={clear}>Clear all</button><button className="primary-button" onClick={()=>apply()}>Apply filters ({activeCount(draft)})</button></footer></aside></>}</section>;
}

function SmartFilterControl({dashboardSlug,filter,values,allValues,onChange}:{dashboardSlug:string;filter:PublishedSmartFilter;values:Value[];allValues:FilterState;onChange:(values:Value[])=>void}){
  const[search,setSearch]=useState("");const[options,setOptions]=useState<Array<{label:string;value:Value}>>(()=>filter.allowedValues.map(value=>({label:String(value),value:value as Value})));const[loading,setLoading]=useState(false);const config=filter.configuration;const asyncSearch=config.searchMode==="SERVER";
  useEffect(()=>{if(!asyncSearch||search.trim().length<config.minimumSearchCharacters)return;const controller=new AbortController();const parents=config.dependsOn.map(filterId=>({filterId,values:allValues[filterId]??[]}));const params=new URLSearchParams({search:search.trim(),page:"1",pageSize:String(config.pageSize),parentFilters:JSON.stringify(parents)});fetch(`/api/published-dashboards/${dashboardSlug}/filters/${filter.id}/options?${params}`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(response.ok)setOptions(body.items??[]);}).finally(()=>setLoading(false));return()=>controller.abort();},[asyncSearch,search,config.minimumSearchCharacters,config.pageSize,config.dependsOn,dashboardSlug,filter.id,JSON.stringify(config.dependsOn.map(id=>allValues[id]??[]))]);// eslint-disable-line react-hooks/exhaustive-deps
  const filtered=asyncSearch?(search.trim().length>=config.minimumSearchCharacters?options:[]):options.filter(item=>item.label.toLocaleLowerCase().includes(search.toLocaleLowerCase()));const multiple=config.selectionMode==="MULTIPLE";
  function toggle(value:Value){if(multiple){const exists=values.some(item=>String(item)===String(value));const next=exists?values.filter(item=>String(item)!==String(value)):[...values,value].slice(0,config.maximumSelectedItems);onChange(next);}else onChange([value]);}
  const selector=<details className="smart-multi"><summary>{values.length?`${values.length} selected`:config.placeholder}</summary>{config.searchable&&<input type="search" value={search} onChange={event=>{const next=event.target.value;setSearch(next);setLoading(asyncSearch&&next.trim().length>=config.minimumSearchCharacters);}} placeholder={asyncSearch?`Type ${config.minimumSearchCharacters}+ characters…`:"Search options…"}/>}<div>{(multiple&&config.allowSelectAll||config.allowClear&&values.length>0)&&<div className="smart-option-actions">{multiple&&config.allowSelectAll&&<button type="button" onClick={()=>onChange(filtered.slice(0,config.maximumSelectedItems).map(item=>item.value))}>Select all shown</button>}{config.allowClear&&values.length>0&&<button type="button" onClick={()=>onChange([])}>Clear</button>}</div>}{loading&&<small>Searching…</small>}{filtered.map(option=><label key={String(option.value)}><input type={multiple?"checkbox":"radio"} checked={values.some(item=>String(item)===String(option.value))} onChange={()=>toggle(option.value)}/><span>{option.label}</span></label>)}{!loading&&!filtered.length&&<small>{asyncSearch&&search.length<config.minimumSearchCharacters?`Enter at least ${config.minimumSearchCharacters} characters` : "No options found"}</small>}</div></details>;
  let control;if(["DATE_RANGE_PICKER","RELATIVE_DATE"].includes(config.controlType)){control=<div className="smart-date-control">{config.controlType==="RELATIVE_DATE"&&<select aria-label={`${filter.name} preset`} onChange={event=>event.target.value!=="CUSTOM"&&onChange(presetRange(event.target.value))} defaultValue="CUSTOM"><option value="CUSTOM">Custom range</option>{config.relativeDatePresets.filter(item=>item!=="CUSTOM").map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select>}<div><input aria-label={`${filter.name} from`} type="date" value={String(values[0]??"")} onChange={event=>onChange([event.target.value,values[1]??event.target.value])}/><span>to</span><input aria-label={`${filter.name} to`} type="date" value={String(values[1]??"")} onChange={event=>onChange([values[0]??event.target.value,event.target.value])}/></div></div>;}else if(config.controlType==="DATE_PICKER")control=<input type="date" value={String(values[0]??"")} onChange={event=>onChange(event.target.value?[event.target.value]:[])}/>;else if(config.controlType==="NUMBER_RANGE")control=<div className="smart-number-range"><input type="number" placeholder="Minimum" value={String(values[0]??"")} onChange={event=>onChange([event.target.value===""?null:Number(event.target.value),values[1]??null].filter(item=>item!==null))}/><span>—</span><input type="number" placeholder="Maximum" value={String(values[1]??"")} onChange={event=>onChange([values[0]??null,event.target.value===""?null:Number(event.target.value)].filter(item=>item!==null))}/></div>;else if(config.controlType==="NUMBER_INPUT")control=<input type="number" value={String(values[0]??"")} onChange={event=>onChange(event.target.value===""?[]:[Number(event.target.value)])}/>;else if(config.controlType==="TOGGLE")control=<select value={String(values[0]??"")} onChange={event=>onChange(event.target.value===""?[]:[event.target.value==="true"])}><option value="">All</option><option value="true">Yes</option><option value="false">No</option></select>;else if(["CHECKBOX_GROUP","RADIO_GROUP","MULTI_SELECT","SEARCHABLE_MULTI_SELECT","ASYNC_SEARCHABLE_MULTI_SELECT","ASYNC_SEARCHABLE_DROPDOWN","SEARCHABLE_DROPDOWN","HIERARCHICAL","CASCADING"].includes(config.controlType))control=selector;else if(config.controlType==="TEXT_SEARCH")control=<input type="search" value={String(values[0]??"")} placeholder={config.placeholder} onChange={event=>onChange(event.target.value?[event.target.value]:[])}/>;else control=<select value={String(values[0]??"")} onChange={event=>onChange(event.target.value?[event.target.value]:[])}><option value="">{config.placeholder}</option>{filter.allowedValues.map(value=><option key={String(value)} value={String(value)}>{String(value)}</option>)}</select>;
  return <div className="smart-filter-field"><label><span>{filter.name}{filter.required&&" *"}</span>{control}</label><small title={config.reason}>{config.controlType.replaceAll("_"," ")}</small></div>;
}
