"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ identifier: data.get("identifier"), password: data.get("password"), rememberMe: data.get("rememberMe") === "on" }) }); const body = await response.json(); setLoading(false); if (!response.ok) return setError(body.error || "ไม่สามารถเข้าสู่ระบบได้"); router.replace(body.redirectTo); router.refresh(); }
  return <main className="auth-page"><section className="auth-panel"><div className="auth-brand"><span className="brand-mark">A</span>atlas<span className="brand-dot">.</span></div><div className="auth-copy"><p className="eyebrow">AI DASHBOARD BUILDER</p><h1>Welcome back</h1><p>Sign in to continue to your analytics workspace.</p></div><form className="auth-form" onSubmit={submit}><label>Email or username<input name="identifier" autoComplete="username" required autoFocus placeholder="you@company.com" /></label><label>Password<input name="password" type="password" autoComplete="current-password" required placeholder="Enter your password" /></label><label className="check"><input name="rememberMe" type="checkbox" /> Remember me</label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</button></form><p className="auth-note">Accounts are created by your administrator. There is no public registration.</p></section><aside className="auth-visual"><div><span>SECURE WORKSPACE</span><h2>One place for every decision.</h2><p>Build dashboards, connect trusted data, and collaborate with role-based access.</p></div></aside></main>;
}
