/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import LoadingState from "@/components/ui/loading-state";

type Schema = { schemaName: string; tableCount: number; viewCount: number; isIncluded: boolean };
type Table = { id: string; schemaName: string; tableName: string; businessName?: string; objectType: "TABLE" | "VIEW"; description?: string; estimatedRowCount?: number; status: string };
type TableResponse = { items?: Table[]; total?: number; page?: number; pageSize?: number; totalPages?: number; error?: string };

function TooltipText({ as: Tag, children }: { as: "small" | "p"; children: string }) {
  return <Tag className="ds-tooltip-text" title={children}><span className="ds-truncated-value">{children}</span><span className="ds-tooltip-popover" role="tooltip">{children}</span></Tag>;
}

export default function MetadataExplorer({ id, canSync }: { id: string; canSync: boolean }) {
  const [schemas, setSchemas] = useState<Schema[]>([]); const [tables, setTables] = useState<Table[]>([]); const [schema, setSchema] = useState(""); const [type, setType] = useState(""); const [query, setQuery] = useState(""); const [q, setQ] = useState(""); const [notice, setNotice] = useState(""); const [syncing, setSyncing] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [totalPages, setTotalPages] = useState(1);

  useEffect(() => { const timer = window.setTimeout(() => { setQ(query.trim()); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [query]);
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(""); const p = new URLSearchParams({ page: String(page), pageSize: "60" }); if (schema) p.set("schema", schema); if (type) p.set("objectType", type); if (q) p.set("q", q); try { const [schemaResponse, tableResponse] = await Promise.all([fetch(`/api/data-sources/${id}/schemas`, { signal }), fetch(`/api/data-sources/${id}/tables?${p}`, { signal })]); const [schemaBody, tableBody] = await Promise.all([schemaResponse.json(), tableResponse.json() as Promise<TableResponse>]); if (!schemaResponse.ok || !tableResponse.ok) throw new Error(schemaBody.error || tableBody.error || "Unable to load metadata"); setSchemas(schemaBody.items ?? []); setTables(tableBody.items ?? []); setTotal(tableBody.total ?? 0); setTotalPages(tableBody.totalPages ?? 1); } catch (loadError) { if ((loadError as Error).name !== "AbortError") setError(loadError instanceof Error ? loadError.message : "Unable to load metadata"); } finally { if (!signal?.aborted) setLoading(false); } }, [id, page, q, schema, type]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  async function sync() { setSyncing(true); setNotice("Connecting and reading Oracle metadata…"); const response = await fetch(`/api/data-sources/${id}/sync`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ syncType: "FULL" }) }); const body = await response.json(); setNotice(response.ok ? `Sync completed: ${body.run.tablesFound} tables, ${body.run.columnsFound} columns` : body.error); setSyncing(false); if (response.ok) await load(); }
  const grouped = useMemo(() => schemas.filter((item) => item.isIncluded), [schemas]);
  return <div className="ds-explorer"><aside><div className="ds-tree-head"><strong>Schemas</strong>{canSync && <Link href={`/data-sources/${id}/schemas`}>Manage</Link>}</div>{grouped.map((item) => <button key={item.schemaName} className={schema === item.schemaName ? "active" : ""} onClick={() => { setSchema(schema === item.schemaName ? "" : item.schemaName); setPage(1); }}><span>▦</span>{item.schemaName}<small>{item.tableCount + item.viewCount}</small></button>)}</aside><section className="ds-explorer-results"><div className="ds-toolbar"><input aria-label="Search metadata" placeholder="Search table or view…" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="Object type" value={type} onChange={(event) => { setType(event.target.value); setPage(1); }}><option value="">Tables & views</option><option>TABLE</option><option>VIEW</option></select>{canSync && <button className="primary-button" disabled={syncing} onClick={() => void sync()}>{syncing && <span className="button-spinner" aria-hidden="true"/>}{syncing ? "Syncing…" : "Sync metadata"}</button>}</div>{notice && <p className={notice.includes("completed") || syncing ? "form-success" : "form-error"}>{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}
    <div className="ds-results-summary"><span>{loading ? "Loading objects…" : `${total.toLocaleString()} objects found`}</span>{totalPages > 1 && <small>Page {page} of {totalPages}</small>}</div>
    <div className="ds-results-stage" aria-busy={loading}>{loading && <div className="ds-loading-overlay"><LoadingState label="Loading metadata objects…" compact/></div>}<div className={`ds-object-grid ${loading ? "is-loading" : ""}`}>{tables.map((table) => { const displayName = table.businessName || table.tableName; const qualifiedName = `${table.schemaName}.${table.tableName}`; const description = table.description || `${table.estimatedRowCount ?? "—"} estimated rows`; return <Link key={table.id} href={`/data-sources/${id}/tables/${table.id}`} aria-label={`${displayName}, ${qualifiedName}. ${description}`}><span className={`ds-object-icon ${table.objectType.toLowerCase()}`}>{table.objectType === "TABLE" ? "▦" : "◫"}</span><div className="ds-object-copy"><strong title={displayName}>{displayName}</strong><TooltipText as="small">{qualifiedName}</TooltipText><TooltipText as="p">{description}</TooltipText></div><em>{table.status}</em></Link>; })}</div>{!loading && !tables.length && !error && <div className="empty">No synchronized objects match your filters.</div>}</div>
    {totalPages > 1 && <nav className="ds-pagination" aria-label="Metadata pages"><button className="secondary-button" disabled={page <= 1 || loading} onClick={() => setPage((current) => Math.max(1, current - 1))}>← Previous</button><span>Page <strong>{page}</strong> of {totalPages}</span><button className="secondary-button" disabled={page >= totalPages || loading} onClick={() => setPage((current) => Math.min(totalPages, current + 1))}>Next →</button></nav>}</section></div>;
}
