"use client";
import { useEffect, useState } from "react";
type Column = { id: string; columnName: string; businessName?: string; dataType: string; nullable: boolean; isPrimaryKey: boolean; isForeignKey: boolean; sensitivityType: string; suggestedSensitivityType: string; status: string; updatedAt: string };
type Detail = { table: { tableName: string; schemaName: string; objectType: string; businessName?: string; description?: string; estimatedRowCount?: number; isIncluded: boolean; status: string; lastSyncedAt?: string; updatedAt: string }; columns: Column[]; indexes: Array<{ id: string; indexName: string; columnName: string; isUnique: boolean; status: string }>; relationships: Array<{ id: string; constraintName: string; relationshipType: string; status: string }> };
export default function TableDetail({ id, tableId, canEdit }: { id: string; tableId: string; canEdit: boolean }) {
  const [detail, setDetail] = useState<Detail | null>(null); const [tab, setTab] = useState("columns"); const [preview, setPreview] = useState<{ columns: Array<{ name: string }>; rows: Array<Record<string, unknown>> } | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/data-sources/${id}/tables/${tableId}`).then((r) => r.json()).then(setDetail); }, [id, tableId]);
  async function loadPreview() { const response = await fetch(`/api/data-sources/${id}/tables/${tableId}/preview`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ rowLimit: 20 }) }); const body = await response.json(); if (response.ok) setPreview(body); else setError(body.error); }
  async function classify(columnId: string, sensitivityType: string) { const response = await fetch(`/api/data-sources/${id}/tables/${tableId}/columns`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ columnId, sensitivityType }) }); if (!response.ok) { setError((await response.json()).error); return; } setDetail((current) => current ? { ...current, columns: current.columns.map((column) => column.id === columnId ? { ...column, sensitivityType, suggestedSensitivityType: "NONE" } : column) } : current); }
  if (!detail) return <div className="empty">Loading table metadata…</div>;
  return <><div className="ds-stat-grid"><article><span>Object</span><strong>{detail.table.schemaName}.{detail.table.tableName}</strong><small>{detail.table.objectType}</small></article><article><span>Estimated rows</span><strong>{detail.table.estimatedRowCount ?? "—"}</strong><small>Oracle statistics</small></article><article><span>Columns</span><strong>{detail.columns.length}</strong><small>{detail.columns.filter((c) => c.isPrimaryKey).length} PK · {detail.columns.filter((c) => c.isForeignKey).length} FK</small></article><article><span>Included for AI</span><strong>{detail.table.isIncluded ? "Yes" : "No"}</strong><small>{detail.table.status}</small></article></div><div className="ds-tabs" role="tablist">{["overview","columns","relationships","indexes","sample","history"].map((name) => <button role="tab" aria-selected={tab === name} key={name} onClick={() => { setTab(name); if (name === "sample" && !preview) void loadPreview(); }}>{name}</button>)}</div>
  {tab === "overview" && <section className="ds-section"><h2>{detail.table.businessName || detail.table.tableName}</h2><p>{detail.table.description || "No description"}</p></section>}
  {tab === "columns" && <section className="table-card">{error && <p className="form-error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Column</th><th>Type</th><th>Nullable</th><th>Keys</th><th>Sensitivity</th><th>Status</th></tr></thead><tbody>{detail.columns.map((c) => <tr key={c.id}><td><strong>{c.businessName || c.columnName}</strong><small className="ds-sub">{c.columnName}</small></td><td>{c.dataType}</td><td>{c.nullable ? "Yes" : "No"}</td><td>{c.isPrimaryKey ? "PK" : ""} {c.isForeignKey ? "FK" : ""}</td><td>{canEdit ? <select aria-label={`Classify ${c.columnName}`} value={c.sensitivityType} onChange={(e) => void classify(c.id, e.target.value)}><option value="NONE">{c.suggestedSensitivityType !== "NONE" ? `NONE · suggested ${c.suggestedSensitivityType}` : "NONE"}</option>{["PERSONAL_DATA","SENSITIVE_PERSONAL_DATA","FINANCIAL","CREDENTIAL","CONTACT","IDENTIFIER","CONFIDENTIAL"].map((value) => <option key={value}>{value}</option>)}</select> : <span className="ds-badge">{c.sensitivityType !== "NONE" ? c.sensitivityType : c.suggestedSensitivityType !== "NONE" ? `${c.suggestedSensitivityType} · suggested` : "NONE"}</span>}</td><td>{c.status}</td></tr>)}</tbody></table></div></section>}
  {tab === "relationships" && <section className="ds-section">{detail.relationships.map((r) => <p key={r.id}><strong>{r.constraintName}</strong> · {r.relationshipType} · {r.status}</p>)}{!detail.relationships.length && <div className="empty">No foreign-key relationships found.</div>}</section>}
  {tab === "indexes" && <section className="table-card"><div className="table-wrap"><table><thead><tr><th>Index</th><th>Column</th><th>Unique</th><th>Status</th></tr></thead><tbody>{detail.indexes.map((item) => <tr key={item.id}><td>{item.indexName}</td><td>{item.columnName}</td><td>{item.isUnique ? "Yes" : "No"}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>}
  {tab === "sample" && <section className="table-card">{error && <p className="form-error">{error}</p>}{!preview ? <div className="empty">Loading masked sample data…</div> : <div className="table-wrap"><table><thead><tr>{preview.columns.map((c) => <th key={c.name}>{c.name}</th>)}</tr></thead><tbody>{preview.rows.map((row, index) => <tr key={index}>{preview.columns.map((c) => <td key={c.name}>{String(row[c.name] ?? "")}</td>)}</tr>)}</tbody></table></div>}</section>}
  {tab === "history" && <section className="ds-section"><h2>Metadata history</h2><p>Last synchronized: {detail.table.lastSyncedAt ? new Date(detail.table.lastSyncedAt).toLocaleString() : "Never"}</p><p>Columns currently marked missing: {detail.columns.filter((c) => c.status === "MISSING").length}</p><p>Last metadata update: {new Date(detail.table.updatedAt).toLocaleString()}</p></section>}</>;
}
