import { z } from "zod";
import { aggregationRuleValues, approvalStatusValues, businessModelStatusValues, businessObjectTypeValues, businessTypeValues, fieldRoleValues, kpiStatusValues, sensitivityLevelValues } from "@/lib/db/schema";
import { formulaNodeSchema } from "./formula";

const tags = z.array(z.string().trim().min(1).max(80)).max(30).default([]);
const nullableText = (max: number) => z.string().trim().max(max).nullable().optional();
export const modelCreateSchema = z.object({ dataSourceId: z.string().uuid(), name: z.string().trim().min(2).max(190), description: z.string().trim().max(4000).optional(), schemaName: z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_$#]*$/) }).strict();
export const modelUpdateSchema = z.object({ name: z.string().trim().min(2).max(190).optional(), description: nullableText(4000), schemaName: z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_$#]*$/).optional() }).strict();
export const modelListQuerySchema = z.object({ q: z.string().trim().max(190).optional(), status: z.enum(businessModelStatusValues).optional(), dataSourceId: z.string().uuid().optional(), page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20) });

export const objectCreateSchema = z.object({ physicalTableId: z.string().uuid(), businessName: z.string().trim().min(2).max(255), shortName: z.string().trim().max(80).optional(), description: z.string().trim().max(4000).optional(), businessDomainId: z.string().uuid().optional(), objectType: z.enum(businessObjectTypeValues).default("UNKNOWN"), recordGrain: z.string().trim().max(500).optional(), dataOwner: z.string().trim().max(190).optional(), dataSteward: z.string().trim().max(190).optional(), tags, sensitivityLevel: z.enum(sensitivityLevelValues).default("INTERNAL"), aiUsageAllowed: z.boolean().default(false), notes: z.string().trim().max(4000).optional(), mapFields: z.boolean().default(true) }).strict();
export const objectUpdateSchema = z.object({ businessName: z.string().trim().min(2).max(255).optional(), shortName: nullableText(80), description: nullableText(4000), businessDomainId: z.string().uuid().nullable().optional(), objectType: z.enum(businessObjectTypeValues).optional(), primaryKeyDefinition: z.unknown().optional().transform((value) => value === undefined ? undefined : JSON.stringify(value)), defaultDateFieldId: z.string().uuid().nullable().optional(), recordGrain: nullableText(500), dataOwner: nullableText(190), dataSteward: nullableText(190), tags: z.array(z.string().trim().min(1).max(80)).max(30).optional().transform((value) => value === undefined ? undefined : JSON.stringify(value)), sensitivityLevel: z.enum(sensitivityLevelValues).optional(), usageStatus: z.enum(["ACTIVE", "DEPRECATED", "HIDDEN"]).optional(), aiUsageAllowed: z.boolean().optional(), approvalStatus: z.enum(approvalStatusValues).optional(), notes: nullableText(4000), layoutX: z.number().int().min(-10000).max(10000).optional(), layoutY: z.number().int().min(-10000).max(10000).optional() }).strict();

export const fieldUpdateSchema = z.object({ businessName: z.string().trim().min(2).max(255).optional(), description: nullableText(4000), businessType: z.enum(businessTypeValues).optional(), fieldRole: z.enum(fieldRoleValues).optional(), aggregationRule: z.enum(aggregationRuleValues).optional(), format: nullableText(80), unit: nullableText(80), currency: nullableText(12), timeZone: nullableText(80), dimensionGroup: nullableText(120), sensitivityClassification: z.enum(["NONE", "PERSONAL_DATA", "SENSITIVE_PERSONAL_DATA", "FINANCIAL", "CREDENTIAL", "CONTACT", "IDENTIFIER", "CONFIDENTIAL"]).optional(), maskingRule: nullableText(80), aiUsageAllowed: z.boolean().optional(), filterable: z.boolean().optional(), groupable: z.boolean().optional(), sortable: z.boolean().optional(), searchable: z.boolean().optional(), visibleToDashboardCreator: z.boolean().optional(), approvalStatus: z.enum(approvalStatusValues).optional() }).strict();

export const relationshipCreateSchema = z.object({ sourceObjectId: z.string().uuid(), sourceFieldId: z.string().uuid(), targetObjectId: z.string().uuid(), targetFieldId: z.string().uuid(), joinType: z.enum(["INNER", "LEFT", "RIGHT"]).default("LEFT"), cardinality: z.enum(["ONE_TO_ONE", "ONE_TO_MANY", "MANY_TO_ONE", "MANY_TO_MANY", "UNKNOWN"]).default("UNKNOWN"), direction: z.enum(["BIDIRECTIONAL", "SOURCE_TO_TARGET", "TARGET_TO_SOURCE"]).default("SOURCE_TO_TARGET"), isRequired: z.boolean().default(false), confidenceScore: z.number().int().min(0).max(100).default(100), sourceType: z.enum(["DATABASE_CONSTRAINT", "AI_SUGGESTED", "MANUAL", "COLUMN_PATTERN"]).default("MANUAL"), notes: z.string().trim().max(4000).optional() }).strict();
export const relationshipUpdateSchema = relationshipCreateSchema.partial().extend({ approvalStatus: z.enum(approvalStatusValues).optional() }).strict();

export const kpiCreateSchema = z.object({ modelId: z.string().uuid(), code: z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9_]*$/).max(80), name: z.string().trim().min(2).max(255), shortName: z.string().trim().max(120).optional(), description: z.string().trim().max(4000).optional(), businessObjective: z.string().trim().max(4000).optional(), businessQuestion: z.string().trim().max(4000).optional(), businessDomainId: z.string().uuid().optional(), owner: z.string().trim().max(190).optional(), dataSteward: z.string().trim().max(190).optional(), tags, measureType: z.enum(["ADDITIVE", "SEMI_ADDITIVE", "NON_ADDITIVE", "RATIO", "COUNT"]).default("ADDITIVE"), formulaAst: formulaNodeSchema, nullHandling: z.enum(["ZERO", "IGNORE", "ERROR"]).default("IGNORE"), divisionByZeroHandling: z.enum(["NULL", "ZERO", "ERROR"]).default("NULL"), decimalPrecision: z.number().int().min(0).max(10).default(2), unit: z.string().trim().max(80).optional(), currency: z.string().trim().max(12).optional(), defaultDateFieldId: z.string().uuid().optional(), dateLogic: z.object({ grain: z.enum(["DAY", "WEEK", "MONTH", "QUARTER", "YEAR"]), mode: z.enum(["CALENDAR", "FISCAL"]).default("CALENDAR") }).strict().optional(), recommendedVisualization: z.string().trim().max(80).optional(), displayFormat: z.string().trim().max(120).optional() }).strict();
export const kpiUpdateSchema = kpiCreateSchema.omit({ modelId: true }).partial().extend({ status: z.enum(kpiStatusValues).optional() }).strict();
export const kpiTestSchema = z.object({ testCaseId: z.string().uuid().optional(), name: z.string().trim().max(190).optional(), inputFilters: z.record(z.string(), z.unknown()).optional(), expectedResult: z.string().trim().max(255).optional(), tolerance: z.string().trim().max(100).optional(), saveTestCase: z.boolean().default(false), technicalValidationNotes: z.string().trim().max(4000).optional(), businessValidationNotes: z.string().trim().max(4000).optional() }).strict();

export const workflowSchema = z.object({ changeSummary: z.string().trim().max(4000).optional(), sourceVersionId: z.string().uuid().optional() }).strict();
export const recommendationReviewSchema = z.object({ decision: z.enum(["ACCEPT", "REJECT"]), modifiedValue: z.unknown().optional() }).strict();
export const glossarySchema = z.object({ modelId: z.string().uuid(), term: z.string().trim().min(1).max(160), definition: z.string().trim().min(2).max(4000), abbreviations: z.array(z.string().trim().min(1).max(40)).max(20).default([]), synonyms: z.array(z.object({ value: z.string().trim().min(1).max(160), language: z.enum(["EN", "TH"]) }).strict()).max(50).default([]), language: z.enum(["EN", "TH"]), businessDomainId: z.string().uuid().optional(), businessObjectId: z.string().uuid().optional(), businessFieldId: z.string().uuid().optional(), kpiId: z.string().uuid().optional() }).strict();

